heroku/heroku-buildpack-nodejs

- README.md
- bin/compile
- bin/test
For backwards compatibility. Some users don't realize they're checking in node_modules so they rely on the `npm install` step to update their dependency tree with current dependencies. Needs more warnings, this is a huge cause of problems.
> run npm install even with prebuild node_modules

- bin/test
- lib/build.sh
It's nice to show which version of npm we're using, even if it's the default.
> test and implementation for always showing npm version

- bin/compile
- lib/build.sh
Instead of changing state, let's leave as much state constant as possible and just read from `node --version` for the caching mechanism.
> avoid updating node_engine state

- bin/compile
Partly resolves https://github.com/heroku/heroku-buildpack-nodejs/issues/185
(at least now you'll know where it was when it failed)
> Log state reads

- lib/build.sh
- test/fixtures/cache-directories/README.md
- test/fixtures/cache-directories/bower.json
- test/fixtures/cache-directories/package.json
- test/run
This is an implementation for #192 allowing people to cache directories like `bower_components`.
> allow users to cache their own directories

- README.md
`heroku config:set` wasn't enough to change the buildpack if you already had one set. Changed it to `heroku buildpack:set` to match the docs here: https://devcenter.heroku.com/articles/buildpacks
> fix(README): heroku buildpack:set not config:set

- lib/cache.sh
- lib/dependencies.sh
- test/run
- remove `npm prune` from prebuilt dependencies
- use `cp` instead of `ln` (`ln` works in test environment, but apparently not on codon)
> Fix prebuild should skip prune

- CHANGELOG.md
- bin/compile
- test/fixtures/iojs/package.json
- test/run
Resolves https://github.com/heroku/heroku-buildpack-nodejs/issues/202
> Fix npm custom installs with iojs

- CHANGELOG.md
- bin/compile
- lib/cache.sh
- test/fixtures/node-0.12.6/README.md
- test/fixtures/node-0.12.6/package.json
- test/fixtures/node-0.12.7/README.md
- test/fixtures/node-0.12.7/package.json
- test/run
Resolves https://github.com/heroku/heroku-buildpack-nodejs/issues/249
Whenever the runtime signature (`node --version; npm --version`) changes, we should invalidate the cache so that dependencies are rebuilt with the new binaries.
> test and implementation to invalidate cache on runtime signature changes

- CHANGELOG.md
- lib/environment.sh
- profile/nodejs.sh
Resolves https://github.com/heroku/heroku-buildpack-nodejs/issues/60
Addresses the previous need to rollback by setting equivalent environments in both the build and run stages. This also shows `NODE_ENV` during build without needing to echo during startup.
A common source of confusion is that npm sets `NODE_ENV=production` anytime `NPM_CONFIG_PRODUCTION=true` or `npm install` is run with the `--production` flag. However, it only sets this for subshells (lifecycle scripts), so outside of npm `NODE_ENV` appears untouched. This PR adds a warning for such scenarios.
This also removes the `WEB_CONCURRENCY` logs from startup, leaving the environment variables set.
> default to NODE_ENV=production for build and runtime

- CHANGELOG.md
- profile/nodejs.sh
This was added in 459ebb67baff09c62fe10d24d9b530915b1da722 and, by the looks of it, mistakenly removed in 043067eb8cc30cfd05115e105c0678c859c12c28.
> Default to NODE_ENV=production during runtime

- profile/nodejs.sh
- test/run
Adds support for the newer, more powerful Performance-L dynos.
Caveat: if apps are not memory-bound (but rather cpu or io bound), or if they have external requirements for fewer worker processes (like limited connections to a database, queue, etc), then this quite-high 28 process concurrency level might overload them. Note this in the docs.
> Performance L

- lib/failure.sh
I noticed that
- there is an additional hyphen, and
- www.npmjs.org redirected to docs.npmjs.com
while working on the support ticket #285287
> Update URL for "node_modules checked into source control"

- lib/output.sh
After the release of npm 3, we had numerous customers run into issues with npm's verbose output (big, nested dep trees) conflicting somehow with `sed` (which is used to format all output in the buildpack). This replaces `sed` with `awk` in the output function for (hopefully) the same output without issues on large builds.
I've tried writing a test to reproduce the `sed` errors without success. I suspect they have something to do with system limits (memory, open files, etc) that are not 1:1 reproduced in the heroku/cedar:14 Docker image used for testing.
> Replace sed with awk

- lib/output.sh
No more monkeying around with `sed`/`tee`/`awk`. Just good old `echo`. Cross-platform, cross-stack, no weird POSIX buffering problems.
> replace tee/sed/awk with a simple echo loop

- CHANGELOG.md
- lib/binaries.sh
- test/run
It's a weird use case but we've seen folks trying to use the node buildpack twice - before and after other buildpacks.
It'd be nice if it just worked in that case.
> test and implementation for compiling the same directory multiple times

- lib/environment.sh
- profile/nodejs.sh
- test/run
PHP users are installing libs that depend on node-which; by prepending `node_modules/.bin` to the `PATH`, the node buildpack essentially replaces the built-in `which` command with a not-quite-the-same node version.
Appending instead of prepending should put these annoying modules after the original binaries in precedence.
/cc @dzuelke
> search node_modules after normal $PATH

- lib/binaries.sh
I've noticed that once in a while, pushes fail during the NPM resolution step and cause the buildpack to fail compilation entirely.  By adding a retry, we can account for occasional "semver" downtime and other transient errors, and potentially avoid failing an application's staging process.
> add retry for curl to resolve NPM version

- lib/binaries.sh
Since the HTTPS URL is available for downloading the Node packages, use that instead of HTTP for better security.
/cc @mbland
> use HTTPS for downloading Node

- lib/output.sh
Very rarely, the container's stdout stream will become unavailable (`echo: write error: Resource temporarily unavailable`). Such an error shouldn't fail the build.
> output stream errors should not fail the build

- CHANGELOG.md
- lib/dependencies.sh
- test/run
https://github.com/heroku/heroku-buildpack-nodejs/issues/282#issuecomment-160877795
Since `npm prune` causes issues when `npm-shrinkwrap.json` is present, we may need to find another mechanism of keeping the cache from bloating. Perhaps a size check + timestamp.
> remove npm prune to work around shrinkwrap issues

- CHANGELOG.md
- bin/compile
- lib/binaries.sh
- lib/failure.sh
- test/fixtures/econnreset-mock/package.json
- test/fixtures/invalid-node/package.json
- test/fixtures/missing-devdeps-1/package.json
- test/fixtures/missing-devdeps-1/postinstall.js
- test/fixtures/missing-devdeps-2/package.json
- test/fixtures/missing-devdeps-2/postinstall.js
- test/fixtures/no-start/package.json
- test/fixtures/no-version/package.json
- test/fixtures/unmet-dep/package.json
- test/run
Adds these warnings:
- missing build dependencies
- missing devDependencies
- missing start mechanism
- ECONNRESET
- unmet dependencies / peer dependencies
To the existing set of warnings:
- invalid package.json
- node engine not/under specified
- prebuilt node_modules
- old npm
- untracked deps (grunt / gulp / bower)
- missing angular resolution
Resolves #319 #316 #310 and #288
> Extended warnings

- CHANGELOG.md
- bin/compile
- lib/cache.sh
- lib/dependencies.sh
- test/run
This reverts one of the changes made Friday: no longer caching `node_modules` by default. Both npm and yarn get enormous performance boosts from existing `node_modules` directories, so it's worth the tradeoff.
For performance reasons, this also removes `yarn check`, which doesn't yet work as documented and in some cases is actually slower than `yarn install`.
I considered replacing `yarn check` with a manual `yarn.lock` diff pre-and-post install, but we saw that in some valid cases enforcing a build failure if `yarn.lock` changed is [not ideal](https://github.com/heroku/heroku-buildpack-nodejs/issues/367), but letting a non-lockfile build pass basically defeats the purpose of having a lockfile in the first place. `--pure-lockfile` and no checking is the best compromise for now.
> Faster cache and check

- lib/binaries.sh
- test/run
Whenever a node version isn't specified, pull down the LTS version (6.x) instead of latest.
> use lts range instead of latest

- profile/nodejs.sh
- test/run
This reverts https://github.com/heroku/heroku-buildpack-nodejs/pull/389 since it affected a few customers negatively.
This reverts commit dd6a5f5aaa9e3a577e77299960c3a5513d1f93e2. Generated with the command: `git revert dd6a5f5aaa9e3a577e77299960c3a5513d1f93e2`
> Revert "Pad WEB_CONCURRENCY with a leading zero"

- bin/test-compile
`YARN_PRODUCTION` doesn't seem to actually be a thing, and changing `NODE_ENV` to something other than `production` is necessary for yarn to install `devDependencies`.
> Remove YARN_PRODUCTION and add NODE_ENV=test to test-compile

- bin/compile
- test/fixtures/yarn-only-engine/package.json
- test/run
Fixes #402 
As long as the user has explicitly defined a yarn version within `package.json` it makes sense for us to download an install it for them, even without a `yarn.lock` file.
Use case:
Desire to use yarn to build a frontend app in a ruby application that's not at the root. Adding a `yarn.lock` to the root doesn't make much sense.
> Make yarn available to application if defined in engines

- bin/compile
- lib/failure.sh
- test/fixtures/dot-heroku-collision-2/.heroku/random-file
- test/fixtures/dot-heroku-collision-2/package.json
- test/fixtures/dot-heroku-collision/.heroku
- test/fixtures/dot-heroku-collision/package.json
- test/fixtures/dot-heroku-node-collision/.heroku/node
- test/fixtures/dot-heroku-node-collision/package.json
- test/run
If a user pushes a source tree that already includes .heroku/node, give a nice warning instead of a crypic error message.
Fixes #371 
Review me please? @hunterloftis @dzuelke @hone
> Check for .heroku/node

- lib/cache.sh
- test/fixtures/cache-prebuild/README.md
- test/fixtures/cache-prebuild/package.json
- test/run
The buildpack should bust the cache whenever the PREBUILD boolean changes to prevent the user from caching their local `node_modules` directory
Fixes #399
> Add $PREBUILD to cache signature

- bin/compile
Fixes #423
Cases:
Not using Yarn:
`yarn.lock` but no version:
`yarn.lock` with version:
> Log out yarn version

- bin/compile
- lib/binaries.sh
- test/fixtures/npm-lockfile-no-version/package-lock.json
- test/fixtures/npm-lockfile-no-version/package.json
- test/run
If the user has not specified a version for npm, but there is a package-lock.json we should automatically install npm 5.
npm v5 is a pretty big diversion from previous iterations in that it has a lock file by default. However our default version is whatever is installed with our Node installation. If the user has specified Node 8 then that will be npm v5, but that's not our default.
If we detect that the user is using npm v5 through the presence of the lockfile we should smartly update them to a version of npm that will respect it, even if they don't define the version themselves.
Fixes #422
> Test for package-lock.json

- lib/binaries.sh
- lib/environment.sh
- lib/json.sh
This switches over to using the new nodebin service to download the Yarn binary. We'll roll this out first and then convert the other binaries over to the new service if things look good.
Notably this will fix #418
> Switch over to using nodebin for yarn

- CHANGELOG.md
- lib/cache.sh
- test/run
Previously new apps (or apps where the cache has been cleared using the heroku-repo plugin) would give a skipping cache restore message of "new-signature" which was slightly misleading.
> Differentiate between an empty cache and a new signature

- CHANGELOG.md
- lib/cache.sh
- test/run
To ensure that the cache is busted when apps update to a new stack.
Fixes #445.
> Add $STACK to the cache signature

- bin/compile
- lib/failure.sh
- test/fixtures/npm-lockfile-old-version/package-lock.json
- test/fixtures/npm-lockfile-old-version/package.json
- test/run
Fixes #428
If a user specified a version of npm a long time ago and forgot about it, but upgrades to npm 5 locally, this will warn them.
> Warn the user if they specify an old version of npm but have a lockfile

- lib/binaries.sh
- test/run
Quick patch for #468 while we work on a better solution.
> manual default for yarn version

- profile/WEB_CONCURRENCY.sh
if an app has a `.profile.d` script that does `set -u`, and that is evaluated before `WEB_CONCURRENCY.sh` (because of alpha order when globbing), the access to the variable, if unset, would cause a failure on startup
the fix is to check if the variable is set, using the `+` parameter substitution
> fix unset LOG_CONCURRENCY crashing apps

- bin/compile
- test/fixtures/npm5/package-lock.json
- test/fixtures/npm5/package.json
- test/run
Fixes #439
Copying the issue text here for context:
> Yarn and npm5 both have cache directories that get defaulted to the $HOME directory on linux. ~/.npm for npm5 and ~/.cache/yarn for yarn.
> This creates an issue for Heroku since $HOME=/app which is the same directory where your application is run. So far this hasn't been a problem because apps are built in a temporary directory, but this will be changing to /app as well in the future. If this were to happen today we'd see a big increase in slug size because the cache directory would be included along with your application.
> It's a bigger issue in Heroku CI in the case of running tests with Jest. Jest will automatically pick up tests in the cache directory, causing your CI tests to fail in hard-to-debug ways when they run fine …
> Move the default Yarn cache directory to a tmp dir

- lib/binaries.sh
Since the last usage of it was removed in #451.
> Remove unused needs_resolution()

- profile/WEB_CONCURRENCY.sh
The `/sys/fs/cgroup/memory/memory.limit_in_bytes` file is now available in both the common runtime and in private spaces.
It contains the actual memory limit of the dyno. 
It's furthermore portable meaning a better default will be set if using the buildpack with Docker.
> Read memory limit

- lib/environment.sh
Fixes #383
Context: A user tried to set `BUILD_DIR` to make the buildpack work for a subdirectory
> Add BUILD_DIR to env var blacklist

- lib/dependencies.sh
In preparing to address #479 I need more metrics around just how many users are going to be affected and how I can best mitigate that.
Currently ~30% of users have a `build` script defined, but only ~10% have a `heroku-postbuild` script. [We've encouraged setting up a `postinstall`](https://blog.heroku.com/node-habits-2017#2-hook-things-up) hook, so I added metrics around that.
> Add more metrics around build scripts

- profile/WEB_CONCURRENCY.sh
- test/run
Fixes #484
With https://github.com/heroku/heroku-buildpack-nodejs/pull/474 we started reading `/sys/fs/cgroup/memory/memory.limit_in_bytes` to get the amount of addressable RAM on the machine and determine a sane value for `WEB_CONCURRENCY`.
However non-Heroku environments may not set this value. In the case of Dokku on Digital Ocean this value exists, but is unreasonably high. This will detect the case where we calculate a ridiculous `WEB_CONCURRENCY` value, default to 1, and print a warning.
> Detect when WEB_CONCURRENCY is way too high

- test/run
At some point I need to rework these tests to not depend on what versions are current, but this will solve the problem for now.
> Fix tests broken by Node 9

- bin/compile
- lib/failure.sh
- test/run
Analysis of build logs gave some more insight into  some common errors that customers are hitting during builds. Let's measure how frequently these happen.
> Add metrics for more types of failures

- bin/compile
I thought this was fixed by https://github.com/heroku/heroku-buildpack-nodejs/pull/459, but not exporting these variables means that they weren't picked up by npm and yarn
> Move the default cache directories for npm and yarn

- bin/test-compile
- ci-profile/nodejs.sh
- lib/environment.sh
- test/fixtures/ci-env-test/README.md
- test/fixtures/ci-env-test/package.json
- test/quick
- test/run
Fixes https://github.com/heroku/heroku-buildpack-nodejs/issues/414 
and
Fixes https://github.com/heroku/heroku-buildpack-nodejs/issues/504
Summary:
In CI, we set `NODE_ENV=test`, but the actual tests would be run at runtime where the `.profile.d` scripts would overwrite it
source: https://github.com/heroku/heroku-buildpack-nodejs/blob/940c813daa56b537008dc0c26bf045d75ff5a4ab/profile/nodejs.sh#L3
This PR fixes that by overwriting `.profile.d/nodejs.sh` with a new startup script, and makes sure this is tested.
> Ci env vars

- lib/dependencies.sh
- test/run
Fixes part of @edmorley's issues in https://github.com/heroku/heroku-buildpack-nodejs/issues/526 by skipping pruning when `NPM_CONFIG_PRODUCTION=true` or `YARN_PRODUCTION=true` since there will be no `devDependencies` to strip away.
> Skip pruning if NPM_CONFIG_PRODUCTION or YARN_PRODUCTION is defined

- test/fixtures/cache-directories/package.json
- test/fixtures/caching/package.json
- test/fixtures/npm-version-range/package.json
- test/run
Ancient npm versions are broken by SSL changes: https://github.com/npm/npm/issues/20203
Other tests are broken because `>=` version requirements resolve to Node 10 now.
> Fix tests broken by Node 10 release and npm changes

- buildpack.toml
- etc/publish.sh
Adds `buildpack.toml` for the buildpack registry and steals the [java buildpack publish script](https://github.com/heroku/heroku-buildpack-java/blob/master/etc/publish.sh)
> Add buildpack.toml and publish script

- test/fixtures/node-10/README.md
- test/fixtures/node-10/package.json
- test/fixtures/node-6/README.md
- test/fixtures/node-6/package.json
- test/fixtures/node-8/README.md
- test/fixtures/node-8/package.json
- test/fixtures/node-9/README.md
- test/fixtures/node-9/package.json
- test/fixtures/yarn/package.json
- test/run
- test/utils
- Yarn reworked the structure of their cache directory with a recent release, which broke one of the tests.
- added new fixtures for Node versions: 6, 8, 9, and 10
- Added new utilities for asserting that a file exists or does not exist after a build
> Fix travis builds

- lib/binaries.sh
- test/utils
Use `"${var:?}"` to ensure this never expands to `/*` .
Double quote array expansions, otherwise they're like `$*` and break on spaces.
Argument mixes string and array. Use `*` or separate argument.
> Fix some Bash issues

- profile/nodejs.sh
- test/run
The resolves an issue where a user that is not using a version of Node supported by the metrics plugin (not 8, 9, or 10) opts in to the feature. 
Since the plugin for the appropriate version of Node is copied into the slug at build time, but the metrics url is set at runtime, we need to verify that the plugin exists before including it.
> Fix issue with old Node and metrics plugin

- etc/hatchet.sh
- makefile
- spec/ci/node_10_metrics_spec.rb
- spec/ci/node_10_spec.rb
- spec/ci/node_6_spec.rb
- spec/ci/node_8_metrics_spec.rb
- spec/ci/node_8_spec.rb
- spec/ci/node_9_metrics_spec.rb
- spec/ci/node_9_spec.rb
- spec/nodebin/node_vX_metrics_spec.rb
- spec/nodebin/node_vX_spec.rb
- spec/spec_helper.rb
These changes move the hatchet ci specs from `specs/` to `specs/ci/` and creates a separate directory with some new specs that mimic the ones for CI, but are designed so that you can specify the Node version via ENV var so that they can be called from nodebin to test new Node releases before making them public
> Add hatchet tests to be called from nodebin service

- lib/environment.sh
This is required to prevent failure during `heroku local:build` which doesn't support writing to the buildpack dir at this time.
> Only write export script if dir is writable

- bin/compile
- lib/output.sh
Currently there's no way to capture the header output if it's piped through `output` because it's automatically indented, which means we can't add any headers inside any of the functions that are piped.
This prevents the header from being indented by matching on the `----->` at the beginning of the line.
> Allow pipeing headers through the log file without indentation

- bin/compile
- lib/cache.sh
- test/run
This splits the logic when the buildpack saves and restores the cache into two separate branches:
- when the user hasn't specified specific directories to cache (most everyone)
- when the user has given a list of specific directories to cache (power users)
This gives us more control over the default messaging, which has included messaging for `bower_components` for every build for a long time. Most users will never use bower, nor should we encourage them to.
These changes silence and minimize the messaging for the default case and gives more detail to those users who have customized
Examples:
```
-----> Restoring cache
- node_modules
-----> Building dependencies
Installing node modules (package.json)
-----> Caching build
- node_modules
```
```
-----> Restoring cache
- node_modules is …
```
> Rework output when caching directories

- bin/compile
- lib/environment.sh
- test/fixtures/print-node-options/README.md
- test/fixtures/print-node-options/package.json
- test/run
Fixes https://github.com/heroku/heroku-buildpack-nodejs/issues/549
We've seen an increasing failures due to frontend build exceeding Node default 1.5GB memory limit during build. Heroku runs these builds on machines with 2.5GB of memory. This increases the default limit for Node 8 and above by passing commands via `NODE_OPTIONS` during build if the user has not set this manually.
The drawback is that once users hit this new limit, there will be nothing they can do to get past it. The current limit currently serves as an early warning system that something might be wrong with your build before it gets too bad.
> Increase Node memory default during builds

- etc/hatchet.sh
When new versions of Node are detected by the `nodebin` service, they are put into a staging bucket and trigger a set of Hatchet tests to be run on Travis CI.
Currently the `etc/hatchet.sh` script that it is running is pulling out the wrong branch. You can see the failing log here: https://travis-ci.org/heroku/heroku-buildpack-nodejs/builds/425495686
```
error fetching custom buildpack https://github.com/heroku/heroku-buildpack-nodejs#tags/v126
```
This change updates the bash script to also trim off the `tags/` from this string, which will reference the tag `v126` which will be valid
```
❯ git name-rev HEAD 2> /dev/null | sed 's#HEAD\ \(.*\)#\1#'
tags/v126
❯ git name-rev HEAD 2> /dev/null | sed 's#HEAD\ \(.*\)#\1#' | sed 's#tags\/##'
v126
```
> Fix branch detection for automated hatchet tests

- bin/compile
- bin/test-compile
- lib/binaries.sh
- lib/cache.sh
- lib/dependencies.sh
- lib/environment.sh
- lib/failure.sh
- profile/WEB_CONCURRENCY.sh
- test/quick
- test/run
- test/utils
Follow-up on #505 
@dzuelke @jmorrell /cc
* Use `$(..)` instead of legacy `´..´`
* Instead of `echo $(cmd)`, just use `cmd`
* Double quote array expansions, otherwise they're like `$*` and break on spaces
* Fix syntax error
* Use `{ cmd1; cmd2; } >> file` instead of individual redirects
* Iterating over `ls` output is fragile, use globs
* `expr` is antiquated, rewrite using `$((..))`
* Use `grep -c` instead of `grep | wc -l`
* Quote to prevent word splitting
> More shell cleaning

- lib/binaries.sh
Some users have reported sporadic failures with yarn `1.10.0`. Pushing the same repository multiple times with no changes resulted in ~30% failure rate during the `yarn install` phase of the build. Note that I could not reproduce this on a local machine.
`1.10.0` is a pre-release version, and ideally we shouldn't be installing it by default yet. See: https://github.com/heroku/heroku-buildpack-nodejs/issues/512 for details.
Let's roll back the default version installed to `1.9.x` temporarily while we look into what is going on with `1.10.0`.
> Default to yarn 1.9.x

- lib/output.sh
- test/unit
Unless `IFS` is adjusted, `read` strips leading and trailing whitespace from each line. In addition, without the `-r` argument to `read`, unescaped backslashes are discarded.
See:
http://mywiki.wooledge.org/BashFAQ/001
Fixes #571.
> Adjust output() so it preserves leading whitespace

- bin/compile
- test/run
The "Cached directories were not restored" message now includes the stack version in the list of possible reasons.
(Technically there is one reason still omitted - `PREBUILD`, however that's more of an edge case, and trying to explain that in the message would lead to it being too verbose.)
> Mention 'stack' in the cache invalidation message

- lib/kvstore.sh
- test/unit
This adds the implementation and unit tests for a key-value store in bash that is serialized to disk
> Add key-value store

- lib/binaries.sh
Now that 1.11.0 is released with https://github.com/yarnpkg/yarn/pull/6413 merged, Heroku users should see fewer failed builds due to 500 responses from the registry.
> Unpin the default Yarn version from 1.9.x

- bin/detect
- test/fixtures/gitignore-package-json/.gitignore
- test/fixtures/slugignore-package-json/.slugignore
- test/run
Before:
```
Node.js: package.json not found in application root
```
After:
```
!     ERROR: 'package.json' listed in '.slugignore' file
!
!     The 'heroku/nodejs' buildpack is set on this application, but was
!     unable to detect a 'package.json' file. This is likely because
!     the '.slugignore' file is removing it before the build begins.
!
!     For more information, refer to the following documentation:
!     https://devcenter.heroku.com/articles/slug-compiler#ignoring-files-with-slugignore
```
```
!     ERROR: 'package.json' listed in '.gitignore' file
! 
!     The 'heroku/nodejs' buildpack is set on this application, but was
!     unable to detect a 'package.json' file. This is likely because
!     the '.gitignore' file is preventing it from being checked in to
!     the git …
```
> Improve bin/detect error messages

- spec/spec_helper.rb
Fixes https://github.com/heroku/heroku-buildpack-nodejs/issues/576
Example failing CI run: https://travis-ci.org/heroku/heroku-buildpack-nodejs/builds/448028570
Nodebin automatically picks up new versions of Node, runs them against our CI suite in this repository and then makes them available on the platform. Currently Node `11.0.0` is failing these runs because it satisfies the `supports_metrics` test when it shouldn't yet. This small change tweaks to the `supports_metrics` predicate to be more accurate.
I will create a follow-up PR that adds a new build of the metrics plugin for Node 11, but this will make it available for now.
> Allow Node 11 integration tests to pass

- test/run
These tests use >= version requirements, so they would break whenever new major versions are released. That's not really necessary, so this removes the bits that will continually break so we don't have to keep bumping them in the future.
> Fix CI tests that dependended on Node 10

- bin/compile
- lib/dependencies.sh
- test/fixtures/build-script-override/README.md
- test/fixtures/build-script-override/package.json
- test/fixtures/build-script/README.md
- test/fixtures/build-script/package.json
- test/run
First step to addressing: https://github.com/heroku/heroku-buildpack-nodejs/issues/583
This adds a new logic branch that will run the 'build' script by default, and run the 'heroku-postbuild' script instead if it is defined.
This branch will not be run for any user yet. Further changes will start to enable this.
> Add new build script behavior behind a flag

- bin/compile
- lib/dependencies.sh
- test/fixtures/build-script-opt-in/README.md
- test/fixtures/build-script-opt-in/package.json
- test/run
Depends on: https://github.com/heroku/heroku-buildpack-nodejs/pull/584
This checks the user's `package.json` for a `heroku-run-build-script` key. If it is set to `true` the new build step will be run instead of the old step, and a message will be printed at the beginning of the build to confirm that is the case.
```
-----> Opting in to new default build script behavior
You have set "heroku-run-build-script" = true in your package.json
- If a "build" script is defined in package.json it will be executed by default
- The "heroku-postbuild" script will be executed instead if present
-----> Creating runtime environment
...
```
> Allow user opt in to build script default behavior

- test/run
Yarn seems to bump the versioned directory it uses for a cache pretty frequently, which causes spurious CI failures, so this moves the test to use a wildcard `*`. 
They still might change the overall structure or the way files are named, but this should result in fewer unrelated CI failures.
> Fix yarn cache tests that are breaking CI

- lib/cache.sh
- test/run
This is a pre-requisite for making better use of the cache.
The current cache layout puts everything that the Node buildpack wants in the cache at: `$CACHE_DIR/node` including custom directories.
This creates a naming issue, since a user could cache anything. We currently keep a cache signature at: `$CACHE_DIR/node/signature`, but if a user declared a custom cache of a `signature` file, these would conflict and break things. 
Adding anything else to the Node cache would make this problem worse, so let's fix it.
This adds one more level where all of the cached directories can live. Now if a user wants to cache a `signature` file, the cache layout would look like this:
```
node/
- cache/
- signature
- signature
```
so there is no longer a conflict.
Deploying this will cause a cache miss for …
> Move cached directories one level down within the node cache

- lib/failure.sh
- test/fixtures/flatmap-stream/package-lock.json
- test/fixtures/flatmap-stream/package.json
- test/run
We've seen a large increase in 404 errors failing builds due to the `flatmap-stream` security issue. Let's add a warning for the users that are hitting this.
> Add warning for flatmap-stream 404 failure

- lib/monitor.sh
- test/mocks/stdlib.sh
- test/unit
There were some issues with using the `monitor` utility discovered in https://github.com/heroku/heroku-buildpack-nodejs/pull/591#discussion_r241261856
`monitor` was collapsing empty arguments and expanding wildcard `*` arguments, leading to some odd behavior. This adds tests and fixes those issues.
> Fix some bugs in the monitor function

- bin/compile
- lib/binaries.sh
- test/run
We almost certainly don't care about the memory usage, but we're not currently tracking the amount of time this takes, and we should be. Re-uses the existing `monitor` command for consistency.
> Add monitoring for binary installations

- lib/kvstore.sh
- test/unit
Allows you to save strings to the `kvstore` without worrying whether they may contain spaces or not
Before:
```
key=value with spaces
```
After:
```
key="value with spaces"
```
> [kvstore] wrap string with spaces

- profile/WEB_CONCURRENCY.sh
- test/unit
In certain CI environments, this value can be misreported, resulting in an invalid initial `MEMORY_AVAILABLE` value.
In these cases, we default the max detected memory to 16GB, or slightly larger than a `performance-l` instance.
> Note: I have a client who has some deployments to Heroku but does not wish to use Heroku CI and currently deploys to GCP, so this fix is so that their CI doesn't throw warnings when they run on servers with 16GB+ memory.
> fix: handle case where memory.limit_in_bytes is nonsensically large

- bin/compile
- lib/build-data.sh
- lib/cache.sh
- lib/dependencies.sh
- lib/failure.sh
- lib/metadata.sh
- lib/monitor.sh
- test/run
This is the first pass at saving build metadata. There are two goals:
- Make the data available in the cache
- output all of the key / value pairs that describe the build onto a single log line in logfmt format
Example use case:
Check how much memory was used in the build step using `bd_get`, and warn users who are getting close to maxing out our build machines so that they are not surprised when they suddenly hit it.
> Save build metadata

- bin/test-compile
- test/fixtures/failing-build/package.json
- test/run
Raised in a support ticket
Currently, if `bin/compile` fails in CI, the `bin/test-compile` script ignores this error return value and continues on to try running the tests.
To fix this, we copy the `set -o errexit` config from `bin/compile` which ensures that the failing command kills execution.
cc and thanks to @ys for raising this concern
> Make sure that failing builds in CI actually fail

- CHANGELOG.md
- bin/compile
- lib/dependencies.sh
- lib/metadata.sh
- test/fixtures/build-script-override/package.json
- test/fixtures/build-script/package.json
- test/run
To be deployed on next Monday (March 11) as part of #583 rollout
Users that will not be affected by this change shouldn't see anything. Those that have a `build` script without a `heroku-postbuild` script will now see a warning at the top of the build log:
Link: https://help.heroku.com/P5IMU3MP/heroku-node-js-build-script-change-faq
Once they opt-in by setting `heroku-run-build-script` to `true` in their `package.json` (which the `npx` command will do for them) they will see a successful opt-in message
```
"scripts": {
"start": "node src/index.js",
"build": "webpack"
},
"heroku-run-build-script": true
```
> Add warning for the upcoming run build change

- lib/dependencies.sh
- lib/json.sh
- test/fixtures/empty-heroku-postbuild/README.md
- test/fixtures/empty-heroku-postbuild/package.json
- test/fixtures/has-script-fixtures/package.json
- test/run
- test/unit
Because of https://github.com/heroku/heroku-buildpack-nodejs/issues/583 it's more important that we can properly detect the presence of a particular build script. Our past method looked at the contents of the script, and would discard empty contents.
This makes sure that even in the case where a `heroku-postbuild` script is completely empty, it will still be preferred over the `build` script.
```
"scripts" : {
"build" : "echo build hook message",
"heroku-postbuild": ""
},
```
> Detect build scripts even when they are empty

- bin/compile
- lib/metadata.sh
- test/run
Currently we're tracking the time spent in parts of the build process, like installing `node_modules` or running the build command, but we're not tracking how long the whole build takes. Let's fix that.
Also removes a stray `new-build-script-opt-in` call that wasn't doing anything
> Log out whole build time

- lib/uuid.sh
- test/unit
Adds a cross-platform compatible command to generate `uuid`s. 
Will eventually move this into https://github.com/heroku/buildpack-stdlib after some time in prod
> Add uuid utility

- bin/compile
- lib/metadata.sh
- test/run
Depends on https://github.com/heroku/heroku-buildpack-nodejs/pull/618
This generates random uuids for both each build run, and the app itself. It then propagates the app uuid through each subsequent build by serializing it into the cache.
This isn't completely ideal because PR apps will each get their own app uuid, but it should still allow us to do better analysis on our log data than we currently can.
Questions like "How many apps failed yesterday?" vs "How many builds failed yesterday"?
The build uuid helps make sure that we aren't ever double counting events somehow.
> Generate UUIDs for the app and build

- bin/compile
- lib/dependencies.sh
- lib/output.sh
Adds a splash of color to the breaking change message to draw attention to it.
> Make breaking change warning header brighter

- CHANGELOG.md
When we upgraded, things broke because `NPM_CONFIG_PRODUCTION` stopped working, however this was not a clear breaking change from the changelog. Thus, I would like to improve the changelog for other users who may also experience this.
> Improve changelog entry for v119

- bin/compile
Similar to #636 
#636 will only print the warning on a successful build. This will print the warning if the build fails, such as if the `build` script does not succeed.
Before:
After:
> Also print the change warning when the build fails

- lib/experiments.sh
- test/unit
- test/unit-fixtures/experiments/experiments-v1
- test/unit-fixtures/experiments/experiments-v1-next
- test/unit-fixtures/experiments/experiments-v2
Adds a way of A/B testing new behaviors. See the very long comment for more detail.
Intended uses for this feature:
- test `npm ci` vs `npm install`
- test between different caching strategies (`node_modules` vs npm / yarn cache)
> New module for running experiments

- bin/compile
- lib/builddata.sh
- lib/failure.sh
- test/run
Depends on #629 
Currently we're only logging data about the build when [the build succeeds](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/compile#L337). This makes sure that we're getting logs for failing builds as well
> Add metadata logging when the build fails

- bin/compile
- lib/dependencies.sh
- test/fixtures/pre-post-build-scripts/package.json
- test/run
Follow-up to https://github.com/heroku/heroku-buildpack-nodejs/pull/625
The prebuild output currently gets lumped in with the `npm install` output:
This separates it out into a new section if it exists:
and skips printing that section if the script is not present:
> Separate prebuild step in log output

- bin/compile
- lib/dependencies.sh
- test/run
These metrics were used to gauge difficulty of the run build breaking change: https://github.com/heroku/heroku-buildpack-nodejs/issues/583 and are no longer useful
Storing them in the metadata so that they get logged out is still useful, so let's keep that.
This also changes the ordering so that it logs out the scripts before they are run, so that if the build fails, the command that failed will also be captured.
> Clean up script metrics and logging

- .travis.yml
- cmd/resolve-version/main.go
- cmd/resolve-version/main_test.go
- go.mod
- go.sum
- makefile
This PR stubs out a go binary and tests. Actual logic will come in later PRs, this just tries to get the machinery in place.
- Adds `cmd` directory for go commands
- Adds `test-binary` and `build` subcommands to `Makefile`
- Makes sure that Travis is running the go tests
```
heroku-buildpack-nodejs git/go-binary-1*  
❯ make build      
github.com/heroku/heroku-buildpack-nodejs/cmd/resolve-version
github.com/heroku/heroku-buildpack-nodejs/cmd/resolve-version
heroku-buildpack-nodejs git/go-binary-1*  
❯ ./vendor/resolve-version-darwin            
hello world
```
> Stub out go binary build and tests

- cmd/resolve-version/main.go
- cmd/resolve-version/main_test.go
- go.mod
- go.sum
Depends on #649 
Adds logic and tests for parsing an S3 url into information about the release.
Example:
input: 
```
node/release/linux-x64/node-v6.2.2-linux-x64.tar.gz
```
output: 
```
{
binary: "node",
stage: "release",
platform: "linux-x64",
url: "https://s3.amazonaws.com/heroku-nodebin/node/release/linux-x64/node-v6.2.2-linux-x64.tar.gz",
version: semver.NewVersion("6.2.2")
}
```
> Add logic for parsing s3 paths

- cmd/resolve-version/main.go
- cmd/resolve-version/main_test.go
Similar to https://github.com/heroku/heroku-buildpack-nodejs/pull/654 but a bit more complicated:
- Node must match the correct platform: `linux-x64` or `darwin-x64`
- Node has special logic around staging releases to enable integration testing
```
heroku-buildpack-nodejs 
❯ curl https://nodebin.herokai.com/v1/node/darwin-x64/latest.txt\?range\=10.x
10.15.3 https://s3.amazonaws.com/heroku-nodebin/node/release/darwin-x64/node-v10.15.3-darwin-x64.tar.gz
heroku-buildpack-nodejs
❯ ./vendor/resolve-version-darwin                                
10.15.3 https://s3.amazonaws.com/heroku-nodebin/node/release/darwin-x64/node-v10.15.3-darwin-x64.tar.gz
heroku-buildpack-nodejs  
❯ curl https://nodebin.herokai.com/v1/node/darwin-x64/latest.txt\?range\=99.x
No result% …
```
> Resolve node versions

- bin/compile
- lib/binaries.sh
- lib/failure.sh
- test/run
This removes support for apps still deploying with io.js. Most weeks see zero deploys of io.js so the impact here is expected to be very small. Those few apps that do deploy with io.js are opening themselves up to very significant security vulnerabilities and should update.
> Deprecate iojs

- README.md
- makefile
Since we're checking the binaries into source, it's important that they are as small as possible. Following the instructions at https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/ we run `upx --brute` over each of the binaries
We see savings of ~70%
Before:
```
❯ ls -lh vendor/resolve-version-*
-rwxr-xr-x  1 jmorrell  SFDC\Domain Users   5.8M Apr 25 16:41 vendor/resolve-version-darwin
-rwxr-xr-x  1 jmorrell  SFDC\Domain Users   5.3M Apr 25 16:41 vendor/resolve-version-linux
```
After:
```
❯ ls -lh vendor/resolve-version-*
-rwxr-xr-x  1 jmorrell  SFDC\Domain Users   1.7M Apr 25 16:33 vendor/resolve-version-darwin
-rwxr-xr-x  1 jmorrell  SFDC\Domain Users   1.6M Apr 25 16:33 vendor/resolve-version-linux
```
> Add new make rule for smaller go binaries

- lib/binaries.sh
- test/run
Follow-up to #661 
This dark-launches the new semver matching logic for determining which Node version to install. The new logic is run alongside the existing logic and it logs out if they return different results.
> Compare new semver logic for node binaries

- bin/compile
- lib/binaries.sh
- lib/failure.sh
- test/run
The dark launched go binary logic is now matching the output of the nodebin service logic. 
This change removes the calls to the nodebin service and switches to the new logic.
> Deprecate nodebin in favor of go binary

- lib/experiments.sh
- test/unit
- test/unit-fixtures/experiments/build-dir-override/heroku-buildpack-experiments
- test/unit-fixtures/experiments/experiments
- test/unit-fixtures/experiments/experiments-v1
- test/unit-fixtures/experiments/experiments-v1-next
Previous PR that introduced this module for context: https://github.com/heroku/heroku-buildpack-nodejs/pull/631
Now that I've started trying to use this module to implement something I ran into some problems with the existing implementation:
- Experiment values differ between CI runs and can create flappy tests
- Explicitly opting in to experiments in tests is complicated
- The "version" idea for defining sets of experiments was overly complicated
- No way of explicitly opt-ing "in to" or "out of" an experiment for any given app other than mucking with the cache
To that end, I've updated this module to be a bit more user-friendly:
- You can check in a special "use these experiments" file into your app. If it's blank, all experiments are turned off
- Save a hash of the schema, when it …
> Refine experiments module

- etc/ci-cleanup.sh
- makefile
When cribbing off of @jkutner for my CI setup, I neglected to copy this cleanup line: https://github.com/heroku/heroku-buildpack-java/blob/master/.travis.yml#L8
which results in hatchet tests occasionally failing in CI due to account limits on number of SSH keys 🙈 
This change adds a cleanup step that should resolve this issue
> Fix issue with too many registered ssh keys

- lib/builddata.sh
- test/run
This was used during the `run build` roll-out but is no longer called anywhere, so let's remove it
> Remove unused code

- experiments
- lib/dependencies.sh
- test/fixtures/node-10-npm-ci-no-lockfile/heroku-buildpack-experiments
- test/fixtures/node-10-npm-ci-no-lockfile/package.json
- test/fixtures/node-10-npm-ci/heroku-buildpack-experiments
- test/fixtures/node-10-npm-ci/package-lock.json
- test/fixtures/node-10-npm-ci/package.json
- test/run
Starts to resolve https://github.com/heroku/heroku-buildpack-nodejs/issues/522
This adds the new logic to use `npm ci` in place of `npm install` for apps that meet the requirements:
- Using npm 6.x or greater
- Have a `package-lock.json`
Here we're rolling this out to 5% of apps to compare the trade-offs in install time. It's likely that this will not result in much benefit until we also change the caching strategy to save the npm cache directory instead of `node_modules`, but let's start with this and gather real-world data instead of guessing.
> npm ci experiment

- bin/compile
- test/run
This logged step gets over-written each time it's set to a new value, but if the build fails, we will be able to see which stage it failed in.
A build that fails during the user-defined build-script stage is very different from a build that fails in the initial setup before user code is even executed. This should allow us to track those separately.
> Add metadata for which step of the build we are in

- CHANGELOG.md
- experiments
Follow-up to #676 
This turns off the CI experiment by changing the rollout to 0% of apps, but keeps the logic in place for further development.
> Turn off npm ci experiment

- lib/binaries.sh
- test/run
After #667 there were a couple of tickets where user builds were failing to resolve Node versions. This was due to an env var `HTTP_PROXY` which is set by the user and could prevent the API requests to `*.amazonaws.com` to fail.
I think there are two options here:
Move the [binary installation step](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/compile#L180) before the [create environment step](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/compile#L119). There are no reasons I can think of that someone would need to set env vars for the binary installation step, but this does run a small risk of breaking someone's build if I'm missing something
or, what this PR does:
set a `NO_PROXY` env var for the version resolution step, which prevents this …
> Avoid proxy issues for version resolution

- bin/compile
Unfortunately, `--silent` suppresses not only output but also errors. `--silent --show-error` will suppress output but still show errors.
I ran into this with a build that was silently failing.
For comparison, before this fix:
```
$ podman run -it --rm -v $(pwd):/tmp/app gliderlabs/herokuish:latest bash
root@1c76891f2133:/# /bin/herokuish buildpack test
-----> Node.js app detected
root@1c76891f2133:/# curl --silent --retry 5 --retry-max-time 15 'https://lang-common.s3.amazonaws.com/buildpack-stdlib/v7/stdlib.sh'
root@1c76891f2133:/#
```
After:
```
root@1c76891f2133:/# /bin/herokuish buildpack test
-----> Node.js app detected
curl: (6) Could not resolve host: lang-common.s3.amazonaws.com
root@1c76891f2133:/# curl --silent --show-error --retry 5 --retry-max-time 15 …
```
> Don't suppress curl errors

- lib/builddata.sh
- test/run
When looking at aggregate builds, it can be hard to know which builds correspond to "toy" apps vs "real" or even "large" apps
One proxy for this can be the # of individual files in the repo. This adds up all of the javascript, typescript, and jsx files and adds that to the build info. This is not expected to be a definitive metric, but to understand approximately how build times change as projects grow.
> Log out number of js, jsx, and ts files

- lib/builddata.sh
Follow up to #686 adding some more filetypes that we didn't track before:
- coffeescript
- vue components
- html files
> Count more filetypes

- bin/compile
This breaks up the previous "install-binaries" build step into `install-nodejs` `install-npm` and `install-yarn` for more fine-grained metadata for failures
> Refine build-step metadata

- CHANGELOG.md
- features
This rolls the changes in #691 out to 5% of apps
> Roll out native yarn caching to a small test group

- spec/fixtures/repos/node-10-metrics/src/index.js
- spec/fixtures/repos/node-11-metrics/src/index.js
- spec/fixtures/repos/node-12-metrics/src/index.js
- spec/fixtures/repos/node-8-metrics/src/index.js
- spec/fixtures/repos/node-9-metrics/src/index.js
- spec/spec_helper.rb
Hatchet metrics tests began failing with Node `12.8.0`. This fixes two issues:
- Node `12.x` wasn't being tested with the metrics plugin before being released because it was being filtered out by [this line](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/spec/spec_helper.rb), which wasn't updated when Node 12 came out. This would have caught the regression when `12.8.0` was released.
- Node `12.8.0` is not firing the `request` `end` event when the response is sent immediately as in the following code:
```
let body = '';
req.on('data', (data) => body += data);
req.on('end', () => Events.emit('metrics', body));
res.statusCode = 200;
res.end();
```
Here, `res.end` is called immediately on receiving the request before the body data uploads and is received. In testing this in …
> Fix hatchet tests due to Node 12.8.0

- features
Follow up to #693 
Issue: https://github.com/heroku/heroku-buildpack-nodejs/issues/665
Initial results are positive but not yet statistically significant. We don't see a big increase in install time or increased error rate, so let's roll this out to half of all apps
> Rollout yarn cache test to more users

- lib/failure.sh
- test/run
The `kb.heroku.come` url schema has changed since these were added. Let's replace them with the short `help.heroku.com` urls which shouldn't change.
> Replace broken kb.heroku.com links with help.heroku.com shortlinks

- bin/report
- test/run
This adds a minimal prototype `bin/report`. I expect `bin/report` itself will evolve rapidly, so the main focus was adding some way of testing this new script.
> Add a minimal version of bin/report + tests

- README.md
- lib/binaries.sh
- test/run
Closes #703
In environments requiring a proxy for all HTTP requests the `NO_PROXY` variable breaks all builds. Because it is being set inline for the command execution there is nothing a user can do to override the value. The issue can be resolved by removing the variable from the script and instead encouraging users to set their environment variables correctly.
I have updated the test to verify that having a proxy and setting the `NO_PROXY` environment variable still allows resolution to occur. I have also added a section to the README detail some of the error messages one might see and what steps they can try.
> Avoid issues in environments requiring proxies for all connections

- lib/dependencies.sh
- test/run
Before:
User script timing and memory metrics were reported like: `postinstall-time`
After:
User script timing and memory metrics were reported like: `postinstall-script-time`
This is more accurate, and `build-time` will no longer conflict with the overall build time. This isn't a user-facing change.
> Rename script monitoring metadata

- bin/compile
- bin/report
- lib/dependencies.sh
- test/fixtures/complex-scripts/README.md
- test/fixtures/complex-scripts/package.json
- test/run
Extends the `bin/report` output with all of the existing metadata we're capturing by looking at project files and pulling stored metadata from the cache
> Extend bin/report

- etc/publish.sh
Extends the publish script to check to make sure that the `buildpack-registry` plugin is installed
If you don't have it installed, it looks like:
```
heroku-buildpack-nodejs git/check-node-plugins-before-publish*  
❯ bash etc/publish.sh                        
Releasing the buildpack requires the buildpack-registry CLI plugin.
https://github.com/heroku/languages-team/blob/master/languages/nodejs/buildpack.md
heroku plugins:install buildpack-registry
Current CLI plugins:
no plugins installed
```
> Add check for CLI plugin to publish script

- CHANGELOG.md
- lib/binaries.sh
- test/run
In line with Node 12 being the active version, this makes the latest version of Node 12 installed unless specified by `.engines.node` from the `package.json`.
> Make Node 12 the default installed version

- CHANGELOG.md
`CHANGELOG` for https://github.com/heroku/heroku-buildpack-nodejs/releases/tag/v166
> CHANGELOG.md entry

- CHANGELOG.md
- Gemfile.lock
Mainly a delayed reaction to [this Excon CVE](https://github.com/heroku/heroku-buildpack-nodejs/network/alert/Gemfile.lock/excon/closed), but also running minor updates to gems for the Ruby tests.
> make minor upgrades to gems

- CHANGELOG.md
- lib/failure.sh
I noticed while poking around that I forgot to set the `failure` key here, so this line is currently a no-op
> Fix missing key when marking failure reason

- CHANGELOG.md
- bin/compile
- lib/failure.sh
- test/run
Warn user when Yarn 2 and NODE_MODULES_CACHE is used. 
This checks for when the user is using Yarn 2 and NODE_MODULES_CACHE and generates a warning that the buildpack won't cache. This PR also removes the use of a fail_yarn2_unsupported method since a failure should not occur if users are using Yarn 2.
> Warn yarn2 with cache

- .travis.yml
- CHANGELOG.md
- README.md
- makefile
To confirm that the buildpack works on the preview of the new stack.
The readme example commands for running the tests have also been fixed to reflect the new makefile target names from #552.
Refs [W-7479929](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000007Qx93IAC/view).
> Add Heroku-20 to the Travis test matrix

- CHANGELOG.md
- spec/ci/node_13_metrics_spec.rb
- spec/ci/node_13_spec.rb
- spec/ci/node_14_metrics_spec.rb
- spec/ci/node_14_spec.rb
- spec/fixtures/repos/node-14-metrics/Procfile
- spec/fixtures/repos/node-14-metrics/index.js
- spec/fixtures/repos/node-14-metrics/package.json
- spec/fixtures/repos/node-14/Procfile
- spec/fixtures/repos/node-14/app.json
- spec/fixtures/repos/node-14/index.js
- spec/fixtures/repos/node-14/package.json
- spec/spec_helper.rb
- repo fixtures for Node 14
- add Node 13 and 14 specs
> add spec support for Node 13 and 14

- CHANGELOG.md
- README.md
Delete proxy issues section from readme to be included in [Dev Center](https://devcenter.heroku.com/articles/nodejs-support)
> delete proxy issues section from readme

- CHANGELOG.md
- bin/compile
- lib/failure.sh
- test/run
User should be warned of build failure if `NO_PROXY` is not set to "amazonaws.com" when `HTTP_PROXY` or `HTTPS_PROXY` is set. See [AWS proxy error](https://devcenter.heroku.com/articles/troubleshooting-node-deploys#aws-proxy-error) section.
> warn if http_proxy/https_proxy set and no_proxy is not aws

- CHANGELOG.md
- bin/compile
- test/run
skip writing to the cache and pruning of the node modules when yarn2 is used
> Skip yarn2 cache prune

- CHANGELOG.md
- bin/compile
- lib/dependencies.sh
- test/fixtures/cleanup-scripts/README.md
- test/fixtures/cleanup-scripts/package.json
- test/run
Add a "heroku-cleanup" script feature that would run at the end of the node build after writing to the cache and pruning the dependencies of devDependencies
See https://github.com/heroku/heroku-buildpack-nodejs/issues/781 for linked issue
> add heroku cleanup script

- CHANGELOG.md
- bin/compile
Makes a feel fixes to the `heroku-cleanup` script that has just been added.
- adding a `cleanup-script` step for bin/report
- outputting the content of the script to $LOG_FILE
> add a cleanup script build step and output to log file

- CHANGELOG.md
- bin/report
- test/run
It seems that the all package managers are being reported as `npm`, so the `if` statement here is not `true`: https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/report#L107, and the reporting is wrong.
This pull request creates a method in `lib/dependencies.sh` to use in both `bin/compile` and `bin/report` to detect for a `yarn.lock` file (and subsequently use Yarn logic).
> use meta_get to get package manager name

- CHANGELOG.md
- bin/compile
- lib/environment.sh
This was causing a bug with Yarn 2 when `YARN_CACHE` was set, which is a reserved env var value. This will also output `USE_YARN_CACHE` at the beginning of the build with the other user-configured build settings.
Blocks https://github.com/heroku/heroku-buildpack-nodejs/pull/795
**Error from Yarn 2 logs**
```
-----> Creating runtime environment
NPM_CONFIG_LOGLEVEL=error
YARN_CACHE=true
NODE_VERBOSE=false
NODE_ENV=production
NODE_MODULES_CACHE=true
-----> Installing binaries
engines.node (package.json):  unspecified
engines.npm (package.json):   unspecified (use default)
engines.yarn (package.json):  unspecified (use default)
Resolving node version 12.x...
Downloading and installing node 12.18.2...
Using default npm version: 6.14.5
Resolving yarn version 1.x...
Downloading and installing …
```
> change env variable from YARN_CACHE to USE_YARN_CACHE

- CHANGELOG.md
- lib/binaries.sh
- test/run
Create the ability to use an environment variable to direct Node binary downloads and Yarn downloads for customization.
See Issue #521 for more info.
> add env var for custom binary url

- CHANGELOG.md
- features
Makes 75% of builds to use npm ci (instead of npm install).
> update npm ci usage to be 75% of new builds

- test/fixtures/npm-prune-5-3-issue/package-lock.json
- test/fixtures/npm-prune-5-3-issue/package.json
- test/fixtures/npm-prune-5-6-issue/package-lock.json
- test/fixtures/npm-prune-5-6-issue/package.json
- test/fixtures/npm5/package-lock.json
- test/fixtures/npm5/package.json
Some of the buildpack tests for npm 5 are failing with Node 12.18.3 (latest 12 release). Therefore, this pull requests locks the Node version at Node 10 for the failing npm 5 tests. While Node <= 12.18.2 seemed to work fine with npm 5, we should encourage users to upgrade to npm 6 when using the active version of Node (currently, 12).
> lock NPM 5 tests to use Node 10 [CHANGELOG SKIP]

- etc/hatchet.sh
- lib/binaries.sh
Lets the hatchet script know to use the base branch when running tests against the buildpack. Also, fixes a typo that made it through tests that are making the hatchet tests for binaries break.
> Set up hatchet script for Circle CI [CHANGELOG SKIP]

- CHANGELOG.md
- lib/binaries.sh
Fixes: https://github.com/heroku/heroku-buildpack-nodejs/issues/512
Those that are using Yarn 1 will get 1.22.x installed when not specified in the package.json with engines. Release candidates for Yarn 1 are coming out less frequently (due to Yarn 2), so if there is a new minor version, it can be updated it accordingly.
Additionally, this will be sure to install Yarn 1.22.x for those that are using Yarn 2 (as it is needed to set the version).
If a new 1.x version comes out, then the default installed version will need to be updated.
> lock yarn installed version at 1.22.x when not specified

- Gemfile
- Gemfile.lock
- etc/hatchet.sh
Following the way the Scala buildpack parallelizes hatchet tests on Circle: https://github.com/heroku/heroku-buildpack-scala/blob/67e2ffdf6a002dd789096ff8ac15eabcc2746d95/.circleci/config.yml#L28-L30
> Parallelize hatchet tests [changelog skip]

- CONTRIBUTING.md
Added contributing guidelines for buildpack contributors ([as pointed out here](https://github.com/heroku/heroku-buildpack-nodejs/pull/811#issuecomment-666341378)). Also, adding hatchet tests for forks to make sure integration tests are run on all pull requests.
> add a CONTRIBUTING.md file for guidelines [changelog skip]

- CHANGELOG.md
- bin/compile
- lib/binaries.sh
- lib/dependencies.sh
- lib/yarn-2.sh
We had some different naming of Yarn 2 references, so this consolidates all of the places where Yarn2 (no space) was used and makes it 2 words.
> Rename yarn2 to yarn 2

- Gemfile.lock
- etc/ci-cleanup.sh
- etc/ci-setup.sh
- etc/hatchet.sh
- makefile
- ActiveSupport's Object#blank? and Object#present? are no longer provided by default (https://github.com/heroku/hatchet/pull/107)
- Remove deprecated support for passing a block to `App#run` (https://github.com/heroku/hatchet/pull/105)
- Ignore  403 on app delete due to race condition (https://github.com/heroku/hatchet/pull/101)
- The hatchet.lock file can now be locked to "main" in addition to "master" (https://github.com/heroku/hatchet/pull/86)
- Allow concurrent one-off dyno runs with the `run_multi: true` flag on apps (https://github.com/heroku/hatchet/pull/94)
- Apps are now marked as being "finished" by enabling maintenance mode on them when `teardown!` is called. Finished apps can be reaped immediately (https://github.com/heroku/hatchet/pull/97)
- Applications that are not marked …
> [changelog skip] Hatchet v7.0.0

- etc/hatchet.sh
- hatchet.lock
Since `master` had been deleted on the `node-js-getting-started` repo, the tests broke. This PR changes the branch name from `master` to `main` for hatchet tests. (It also removes skipping of hatchet tests on forks as this process will be added as a manual step... docs to come).
> Fix CI runs [changelog skip]

- README.md
- etc/publish.sh
It's not clear from docs that `main` does not correspond with the latest release version, so if someone wants the latest release and use the git url, we should have a "latest" tag that is the most up-to-date release.
Per https://github.com/heroku/heroku-buildpack-nodejs/issues/856
- add to README about using the buildpack registry version of the buildpack and pinning to latest
- update publish command to tag and push a latest release
> Add a latest tag to buildpack releases [changelog skip]

- CHANGELOG.md
- lib/dependencies.sh
- test/run
Add a NODE_BUILD_FLAG environment variable that can be used by the user to set build flags for the build script.
> add build flag option

- CHANGELOG.md
- inventory/node.toml
Security Release Notes: https://nodejs.org/en/blog/vulnerability/november-2020-security-releases/
> add 12.19.1, 14.15.1, and 15.2.1 to inventory for security releases

- .circleci/config.yml
- etc/ci-setup.sh
Match Ruby and bundler version to the versions of the internal sync versions.
> Remove bundler version and change Ruby version [changelog skip]

- CHANGELOG.md
- lib/dependencies.sh
- lib/monitor.sh
- test/run
Fixes the previously implemented customizable build flag with the following:
- adds the `--` for adding flags to npm scripts
- adds an `else` for executing a yarn script without flags
- changes env var to `NODE_BUILD_FLAGS`
> move build flags into script name string

- .circleci/config.yml
- Gemfile.lock
Upgrades Ruby and Bundler for use on CI for hatchet tests.
> upgrade to use Ruby 2.7.x and Bundler 2 [changelog skip]

- CHANGELOG.md
- lib/dependencies.sh
- test/fixtures/ng-build-script/README.md
- test/fixtures/ng-build-script/package.json
- test/run
Warn users of having `ng build` in their build script. Recommend using node build flags --prod instead.
> add warning for ng build script

- CHANGELOG.md
- bin/report
- lib/binaries.sh
Right now, the `resolve` binary prints to `$STD_ERR` instead of `$STD_OUT`. This change will write the parsing errors the reporting file and send them to internal reporting.
> Report resolve parse error

- CHANGELOG.md
- inventory/node.toml
- test/run
Update node.js inventory to supply security releases: https://nodejs.org/en/blog/vulnerability/january-2021-security-releases/
> Add Node security releases to inventory

- CHANGELOG.md
- lib/binaries.sh
- test/run
With Node 14 as the current active version, we will install the latest version of Node 14 as default.
> change node version to 14

- CHANGELOG.md
- test/unit
This buildpack is inconsistent with [the heroku/ruby buildpack's setting
of WEB_CONCURRENCY][1]. It tries to guess a reasonable value for
WEB_CONCURRENCY, even if one is set manually in the application's
configuration.
Since this value is used, by default, [by the Puma web server][2], this
behavior is undesirable. Newer Rails applications use both the
heroku/nodejs buildpack and the heroku/ruby buildpack because Rails
manages assets through Webpack.
This change respects any value that the customer sets for
WEB_CONCURRENCY via `heroku config:set` instead of blindly overwriting
the value. With this behavior, the customer can better control the
process-level concurrency for their applications.
I verified that this behavior does, indeed, occur by doing the
following:
1. `heroku config:set …
> Add unit tests around WEB_CONCURRENCY

- CHANGELOG.md
- lib/failure.sh
This adds a build-time ended k/v pair to the build reporting right before the build fails.
> log the build time before the build fails

- CHANGELOG.md
- lib/dependencies.sh
- lib/yarn-2.sh
- test/run
Fixes: https://github.com/heroku/heroku-buildpack-nodejs/issues/904
> fix return value for detecting yarn workspace plugin

- .circleci/config.yml
- CHANGELOG.md
- README.md
- makefile
The Heroku-16 stack reached end-of-life on May 1st, 2021, and from June 1st, 2021, builds will be disabled.
This removes support for testing against Heroku-16 in CI.
This change is non-breaking as it only affects development (hence why it's landing a few days early), however a changelog entry has been added regardless, for improved visibility into the support status of the stack.
Closes GUS-W-9329672.
> Drop Heroku-16 from CI test matrix

- makefile
In production `STACK` is always set to `heroku-{16,18,20}` even for the `-build` stack image variants.
Spotted whilst working on #920.
> Tests: Use the correct value for STACK during integration tests [changelog skip]

- CHANGELOG.md
- profile/WEB_CONCURRENCY.sh
- test/unit
Changes the various functions around so they no longer have side effects.
> Refactor $WEB_CONCURRENCY handling

- CHANGELOG.md
- inventory/node.toml
- inventory/yarn.toml
- test/fixtures/cache-directories/bower.json
- test/fixtures/cache-directories/package.json
- test/run
- test/shunit2
- test/unit
- test/utils
There have been some recent failures in CI. This PR fixes the following issues:
1)
```
testBuildWithUserCacheDirectories
ASSERT:expected:<1> but was:<0>
```
This appears to be due to using an ancient and vulnerable version of jQuery in the `cache-directories` fixture. I've updated the `node`, `bower`, and `jQuery` versions for this fixture.
2)
```
ASSERT:Expected </tmp/tmp.zHnCba0e4H> to contain <resolve-v1-yarn="1.22.10 https://s3.amazonaws.com/heroku-nodebin/yarn/release/yarn-v1.22.10.tar.gz">
ASSERT:Expected </tmp/tmp.zHnCba0e4H> to contain <resolve-is-equal-yarn=true>
```
This was due to a newer release of yarn becoming available, 1.22.11. The problem here is twofold. 1) inventory/yarn.toml needs the new entry 2) these tests were not tolerant to version changes.
3)
Additionally, this …
> Fix broken tests; bump shUnit2 to 2.1.8

- CHANGELOG.md
- lib/binaries.sh
Fixes https://github.com/heroku/heroku-buildpack-nodejs/issues/927
Maintains backward compatibility with anyone who set up a custom tarball with an embedded misnamed folder like `node-v-linux-x64` by stripping the initial path component unconditionally rather than baking in an assumption about what that path component will look like.
> Fix NODE_BINARY_URL extraction

- CHANGELOG.md
- Gemfile.lock
- spec/spec_helper.rb
Recent pull requests are failing in CI, due to hatchet installation failures. I'm upgrading hatchet here to get CI green again.
Example failures:
- https://app.circleci.com/pipelines/github/heroku/heroku-buildpack-nodejs/294/workflows/c3e91594-980a-4c15-b331-c81eb8d0a063/jobs/2016
- https://app.circleci.com/pipelines/github/heroku/heroku-buildpack-nodejs/292/workflows/8516bef5-4011-41d0-980a-a3bcb5547308/jobs/2009
> Upgrade to latest heroku_hatchet (7.3.4)

- .github/workflows/check_changelog.yml
The current changelog check is not skippable. That's annoying and muddies up the changelog when PRs have no real user-facing changes that require documentation. 
This brings in the check from https://github.com/heroku/cutlass (as mentioned in https://github.com/heroku/heroku-buildpack-nodejs/pull/936#issuecomment-910432910) that has the functionality we are looking for.
> Update changelog check to be skippable

- CHANGELOG.md
- lib/dependencies.sh
- test/fixtures/node-10-npm-ci-shrinkwrap/npm-shrinkwrap.json
- test/fixtures/node-10-npm-ci-shrinkwrap/package.json
- test/run
Original reasoning, discussion and so on is on the PR #899.
I'm just opening this new PR because for some reason Github didn't recognize the new commit on the fork.
> Add support for running "npm ci" when "npm-shrinkwrap.json" is found on the project directory

- CHANGELOG.md
- inventory/node.toml
There have been a few new node releases since this files last update (such as 12.22.6, 14.17.6, 16.8.0, 16.7.0). While updating this file, I noticed that we were missing a fair number of older releases. The script that generates this file was not iterating through all the pages of the S3 bucket. This list now includes everything available from our mirror, including the additional pages.
> Update node inventory to include previously truncated versions

- CHANGELOG.md
Since it was published the day after the currently listed date:
```
$ h buildpacks:versions heroku/nodejs | head -n3
Version  Released At               Status
───────  ────────────────────────  ─────────
188      2021-09-10T17:03:08.056Z  published
```
> Update changelog release date for v188

- CHANGELOG.md
- bin/compile
Reverts heroku/heroku-buildpack-nodejs#888
There have been more than a few reports of trouble building with Yarn after this change. It doesn't seem to be working as expected. For example:
- https://github.com/heroku/heroku-buildpack-nodejs/issues/943
- https://github.com/heroku/heroku-buildpack-nodejs/issues/884#issuecomment-915783387
- https://heroku.support/1027280
> Revert "Always use local yarn cache with yarn 2"

- CHANGELOG.md
- inventory/yarn.toml
To fix CI on `main`, now that there are newer Yarn versions, which cause `testBuildMetaData` to fail, the same as it did in #934.
Example failure:
https://app.circleci.com/pipelines/github/heroku/heroku-buildpack-nodejs/341/workflows/ec520072-c915-4dba-8fe3-ffe1f2197e8f/jobs/2277
GUS-W-9981764.
> Add Yarn 1.22.1{2,3,4,5} to inventory/yarn.toml

- Gemfile
- Gemfile.lock
- Removed unused `parallel_tests` dependency (this repository is using `parallel_split_tests` instead).
- Refreshes `Gemfile.lock` to pick up new dependencies. Moving forwards Dependabot will take care of this, but doing so in one go reduces the PR churn to get the repo up to date. Mass-updating is safe since the Ruby deps are only used in CI.
GUS-W-9981100.
> Remove unused parallel_tests gem & refresh Gemfile.lock

- inventory/node.toml
- inventory/yarn.toml
This updates the list of node and yarn versions to what is available in nodebin. This should address some of the CI failures in other PRs.
> Update node and yarn inventory

- CHANGELOG.md
- lib/binaries.sh
- test/run
This will change the default version of Node.js that is installed when an app does not specify a `node` version in `package.json`'s `engines`.
Node.js 16 is the current Active LTS, so this would bring us up to date with our posted [support policy](https://devcenter.heroku.com/articles/nodejs-support#supported-runtimes).
Resolves #972 .
GUS-W-10500401
> Update default node version to 16.x

- inventory/node.toml
- spec/spec_helper.rb
This updates the inventory with currently available versions as of today.
It also updates our version resolver tests to test against Node.js versions that still get releases (10 and 15 are no longer supported).
> Chore: Update Inventory

- CHANGELOG.md
- lib/cache.sh
It looks like the current yarn cache save logic (introduced in #978) creates nested caches like this:
```
- node
- cache
- yarn
- yarn
- yarn
- yarn
```
This PR changes the cache save logic to replace the existing yarn folder in the cache, rather than creating a directory inside.
GUS-W-10519616
> Replace yarn cache rather than nest it

- CHANGELOG.md
- lib/cache.sh
The current yarn cache restore logic (introduced in #978) can create nested caches like below, iff the `.yarn/cache` folder is committed in the repo, but empty.
```
- node
- cache
- yarn
- yarn
- yarn
- yarn
```
This PR changes the cache restore logic to remove the empty folder before moving the cache, so we essentially replace the folder, rather than nesting folders.
This also adds some temporary logic to delete any nested caches we created in #978.
GUS-W-10519616
> Fix additional occurrence of yarn cache nesting

- CHANGELOG.md
- inventory/yarn.toml
Noticed this was causing CI failures after merging #990.  This should get the failing tests sorted.
> Added inventory entry for yarn 1.22.18

- CHANGELOG.md
- bin/compile
- bin/detect
For debugging or for folks who are curious about how the buildpack works.
Similar implementation here: heroku/heroku-buildpack-python#226
> feat: set xtrace if $BUILDPACK_XTRACE set

- .github/workflows/check_changelog.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> Set permissions for GitHub actions

- lib/binaries.sh
When a new version of npm is installed only the specified compatible version is logged, not the resolved/installed one. This differs from when installing Node, where both versions are logged. Logging the exact version helps in debugging and adds clarity.
Before:
```sh
Resolving node version ~16...
Downloading and installing node 16.14.2...
Bootstrapping npm ~8 (replacing 8.5.0)...
npm ~8 installed
```
After:
```sh
Resolving node version ~16...
Downloading and installing node 16.14.2...
Bootstrapping npm ~8 (replacing 8.5.0)...
npm 8.6.0 installed
```
> Log exact installed npm version

- .circleci/config.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- makefile
- spec/hatchet/stack_spec.rb
The Node.js binaries are not stack-specific, so no buildpack/binary changes are needed for Heroku-22 - only testing it in CI.
GUS-W-10343867.
> Add Heroku-22 to the CI test matrix

- CHANGELOG.md
- bin/compile
- lib/dependencies.sh
- lib/failure.sh
- test/run
The [Node support docs](https://devcenter.heroku.com/articles/nodejs-support#skip-pruning) state that Yarn dependency pruning can be skipped by setting `YARN_PRODUCTION=false` but this only works with Yarn v1 since using the `YARN_PRODUCTION` environment variable with Yarn v2+ will cause `yarn` commands to fail.
This PR will:
* detect when Yarn v2+ is used in the build and raise an actionable error if `YARN_PRODUCTION` is set
* checks for the presence of a `YARN2_SKIP_PRUNING` environment variable to determine if we should skip pruning or not
Fixes #1007
> Fix for skipping pruning with Yarn 2

- CHANGELOG.md
- bin/compile
- lib/cache.sh
- lib/dependencies.sh
- test/fixtures/ci-caching/README.md
- test/fixtures/ci-caching/package-lock.json
- test/fixtures/ci-caching/package.json
- test/run
Since `npm ci` removes any existing `node_modules` folder before installing, to get proper caching behavior we need to cache the npm cache instead.
Fixes #1006
> Fix for npm ci caching

- CHANGELOG.md
- lib/json.sh
Since `jq` now exists on all stacks:
https://devcenter.heroku.com/articles/stack-packages
Removing since this means one fewer `curl` call to which retries etc have to be added shortly.
> Remove optional `jq` install step

- CHANGELOG.md
- lib/binaries.sh
- lib/failure.sh
In the shimmed CNBs used in `heroku/builder` we have been seeing quite a few transient errors related to buildpacks downloading from S3.
Adding appropriate retries and connection timeouts to all of our buildpack's curl usages should help with these, as well as make builds more reliable in general for users on Heroku, plus also anyone using a shimmed CNB locally with Pack CLI (where the network connection may be even less reliable).
The `--retry-connrefused` option has been used since otherwise curl doesn't retry cases where the connection was refused. Ideally we would use `--retry-all-errors` which takes that one step further, however that option was only added in curl 7.71, so is only supported by Heroku-22+.
For more on curl options, see:
https://curl.se/docs/manpage.html …
> Adjust curl retry and connection timeout handling

- inventory/node.toml
- inventory/yarn.toml
This brings the inventory up to date with https://github.com/heroku/buildpacks-nodejs.
> Update Node.js inventory

- etc/ci-setup.sh
- etc/hatchet.sh
Part of the workflow for mirroring node.js asset releases includes running the hatchet tests defined here. Over in https://github.com/heroku/nodebin/pull/183, I'm converting that mirroring process to GitHub Actions. The `etc/hatchet.sh` and `etc/ci-setup.sh` scripts are setup for use in CircleCI environments, but not in GitHub Actions environments. This PR adjusts the scripts to work in both CircleCI and GitHub Actions, and drops support for Travis, which we haven't used for some time now.
> Support GitHub Actions in etc scripts

- CHANGELOG.md
- lib/failure.sh
- test/run
Since:
- The app is deprecated and due to be switched off shortly.
- The buildpack should have as few dependencies on external resources as possible (particularly those not productionised or behind CDN).
- We especially should not have dependencies on `herokuapp.com` domains, given the reduced flexibility and risk of subdomain takeover.
Fixes #1015.
GUS-W-11843580.
> Remove dependency on semver.herokuapp.com

- .github/workflows/ci.yml
- CHANGELOG.md
- lib/binaries.sh
- test/run
This will change the default version of Node.js that is installed when an app does not specify a `node` version in `package.json`'s `engines`.
Node.js 16 is a "Maintenance LTS" as of 2022-10-18. Node.js 18 becomes the "Active LTS" on 2022-10-25 ([Node.js Releases](https://nodejs.dev/en/about/releases/)). As of today, there isn't an "Active LTS", so we're in a short window where there isn't an "Active LTS". But, Node.js 18 is a "Current" version, so updating the default to 18 would keep our default within our posted [version support policy](https://devcenter.heroku.com/articles/nodejs-support#supported-runtimes).
However, Node.js 18 and newer are incompatible with `ubuntu:18`/`heroku-18`, due to a `gcc` version incompatibility. Changing the default on `heroku-18` would likely cause failing …
> Change the default Node.js to 18.x

- CHANGELOG.md
- bin/compile
- test/fixtures/yarn-2-with-engine/package.json
- test/run
Yarn berry (yarn 2.x and greater) releases are being made available in Heroku's yarn mirror. This should allow yarn berry projects to install a yarn berry CLI, rather than using the yarn classic (`1.22.x`) CLI as a proxy. When the releases are made available, users could select a specific release with `engines.yarn` in `package.json` like this:
```
{
“engines”: {
“yarn”: “3.4.x”
}
}
```
In this scenario, the "You don't need to specify Yarn engine" warning messages no longer make sense. This PR removes that messaging and restriction.
> Allow yarn version selection for yarn berry projects

- .github/workflows/inventory.yml
This adds automatic inventory updates automation via GitHub actions. This is nearly identical to what we have in https://github.com/heroku/buildpacks-nodejs/blob/main/.github/workflows/inventory.yml, except that the binaries must be installed from git, and the paths to the inventories and changelogs are different. This automation will check for new node and yarn binaries that exist in our mirror, add them to the inventory, and open a pull request if there are any changes.
Example PRs as a result of this automation: https://github.com/heroku/heroku-buildpack-nodejs/pull/1073, https://github.com/heroku/heroku-buildpack-nodejs/pull/1072
[W-10657880](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000m3GcWYAU)
> Add inventory update automation

- .github/workflows/inventory.yml
This is a followup fix to #1071. 
- The changelog wasn't getting updated on inventory changes because it expected `[Unreleased]` heading (like the CNB has), but the header here is `## main`.
- The PR descriptions and titles referenced CNB buildpack names, not this buildpack.
> Fixup minor issues with inventory automation

- .github/workflows/inventory.yml
As noted in https://github.com/heroku/heroku-buildpack-nodejs/pull/1076#issuecomment-1486798132, the yarn inventory updates weren't making it into the changelog. The changelog step edit in #1074 only applied to the node.js job, not the yarn one.
> Fix yarn inventory automation changelog step

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- lib/binaries.sh
- makefile
- spec/ci/node_18_spec.rb
- spec/ci/node_19_spec.rb
- spec/ci/node_20_spec.rb
- test/run
As documented [here](https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq), heroku-18 is no longer supported for builds on heroku. This PR drops all references and special casing for the now end-of-life stack.
Several of our integration tests were failing, since they relied on heroku-18 builds, which are no longer available. This should put the CI pipeline back in working order.
> Drop all references and special casing for heroku-18

- CHANGELOG.md
Prepares v212 for release, which will include:
- node version 20.1.0.
- yarn versions 4.0.0-rc.43, 3.5.1.
- Drop all support and references to the `heroku-18` stack.
> Prepare v212 release

- .github/workflows/inventory.yml
Inventory automation has been failing ([example](https://github.com/heroku/heroku-buildpack-nodejs/actions/runs/5262905080)), because `list_versions` is now `generate_inventory` as of https://github.com/heroku/buildpacks-nodejs/pull/524.
> Use new binary name from heroku/buildpacks-nodejs

- spec/spec_helper.rb
CI has been failing (example: https://github.com/heroku/heroku-buildpack-nodejs/actions/runs/5314918171/jobs/9638438314) due to the hatchet tests assuming an app's `web_url` to be `#{app_name}.herokuapp.com`. That's not always the case anymore. See the Heroku changelog entry that describes the new naming scheme: https://devcenter.heroku.com/changelog-items/2640.
> Use the web_url to ensure we use the new domain names

- CHANGELOG.md
#1112's changelog missed a few versions. Something is up with the changelog generation.
> Add missing Node.js releases to changelog

- etc/publish.sh
`etc/publish.sh` does a check to make sure the `buildpack-registry` plugin is installed. However, `heroku plugins` hasn't been reliably listing `buildpack-registry` as a plugin, even when the commands from the `buildpack-registry` plugin are present and available, so this bit of code has been blocking releases.
> Drop the plugin check; it's no longer working

- CHANGELOG.md
This prepares v216, which will include new Node.js and Yarn versions.
> Prepare v216 for release

- CHANGELOG.md
This will bring in new Node.js versions `20.6.0` and `20.6.1`.
> Prepare release v220

- CHANGELOG.md
- lib/binaries.sh
- test/fixtures/npm-version-incompat/README.md
- test/fixtures/npm-version-incompat/package.json
- test/run
When installing `npm@10` with `node@16`, users are seeing error messages like this: `Unable to install npm >=9; does it exist?`.
The issue here is that `npm@10` has minimum requirements for the Node.js version it works with: https://github.com/npm/cli/blob/3f9aa452061cde22de1babb33fd9bed8f2b6e3a5/package.json#L257
The `npm` command emits an error message explaining the issue that looks like this:
```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@10.0.0
npm ERR! notsup Not compatible with your version of node/npm: npm@10.0.0
npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
npm ERR! notsup Actual:   {"npm":"8.5.0","node":"v16.14.0"}
```
However, due to the use of shell redirection in the buildpack, the …
> Improve error messaging when installing an incompatible npm version

- CHANGELOG.md
- lib/binaries.sh
Dropping stderr/stdout on the floor results in mysterious buildpack failures in certain cases. For instance, if there is a `.yarnrc.yml` that requires an environment variable, `yarn --version` will output an error, but then the existing code would just silence that, causing users to think that the yarn install failed with no real recourse.
> fix: do not ignore errors when checking npm/yarn output

- .github/workflows/inventory.yml
Currently the inventory update PRs don't use the bot user for the commit author, but instead the Josh's user, eg:
https://github.com/heroku/heroku-buildpack-nodejs/pull/1150/commits/9bd0ec175def5bbd4f88e155345eb4cea0f13be5
Now the author is set to our bot user, the same way we do in other repos, eg:
https://github.com/heroku/languages-github-actions/blob/5dde4b7d832209dc8d6862d083a41a18d72c7c32/.github/workflows/_buildpacks-prepare-release.yml#L104-L106
In addition, the `automation` label is no longer set, for the same reasons as:
https://github.com/heroku/languages-github-actions/pull/109
GUS-W-14283836.
> Fix author/committer for inventory update PRs

- .github/workflows/inventory.yml
Multiline strings need to be captured using a [delimiter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings).  Otherwise the diff output gets truncated to a single line.
> Fixes multiline output not being stored correctly

- CHANGELOG.md
- inventory/yarn.toml
This reverts commit 87820636e63fbd5c78389e1531516d71ff927b63 (#1163).
Yarn 4 builds aren't working, as shown in the CI failures here: https://github.com/heroku/heroku-buildpack-nodejs/pull/1164. This will remove yarn 4 from the inventory, which should prevent those builds. We can bring yarn 4 back in once builds are working again.
> Drop yarn 4 from inventory

- CHANGELOG.md
This will release new Node.js and Yarn versions.
- Added Yarn version 4.0.0.
- Added Node.js version 21.1.0.
- Added Node.js version 20.9.0.
> Prepare release v227

- CHANGELOG.md
- lib/binaries.sh
- test/run
As of [2023-10-24](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#2023-10-24-version-2090-iron-lts-richardlau), Node.js 20.x is now the LTS version.
[W-14390734](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001dS1fkYAC/view)
> Update default Node version to 20.x

- CHANGELOG.md
This marks support for Node.js 21.5.0 under the 233 release.
> Document v233 release

- CHANGELOG.md
This will release Node.js 20.11.0 under the v234 tag.
> Prepare release v234

- CHANGELOG.md
- profile/WEB_CONCURRENCY.sh
- test/unit
This allows the WEB_MEMORY / WEB_CONCURRENCY selection to be more appropriate on memory heavy instances.
[GUS](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001g8anxYAA/view)
> Adjust WEB_CONCURRENCY for memory heavy instances

- .github/workflows/inventory.yml
- CHANGELOG.md
This PR cleans up CHANGELOG.md to better match the format expected by the automation added in #1200. This will allow for release links to be created which we were not doing with our manual process.
> Cleanup CHANGELOG.md

- .github/CODEOWNERS
Corrects the inventory-file related `CODEOWNERS` entry to match the actual naming of the files in this repo:
- `inventory/node.toml`
- `inventory/yarn.toml`
(Only the CNB uses `inventory.toml`)
GUS-W-14941625.
> Update inventory related entries in CODEOWNERS

- .github/CODEOWNERS
The entries added in #1205 were accidentally the CNB version of the file (that had `Cargo.lock` etc), not the classic buildpack version of the file that has `Gemfile.lock`.
This corrects #1214 requesting review from the team rather than the language owners.
> Fix classic vs CNB specific entries in CODEOWNERS

- bin/compile
- lib/binaries.sh
- lib/cache.sh
- test/run
These changes build on top of [existing pnpm support](https://github.com/heroku/heroku-buildpack-nodejs/pull/1224) to allow `pnpm` dependencies to be saved and restored between builds.
> Add pnpm caching

- bin/compile
- lib/failure.sh
- test/fixtures/pnpm-bad-engine/.gitigore
- test/fixtures/pnpm-bad-engine/.npmrc
- test/fixtures/pnpm-bad-engine/package.json
- test/fixtures/pnpm-bad-engine/pnpm-lock.yaml
- test/fixtures/pnpm-bad-engine/server.js
- test/fixtures/pnpm-engine/.gitigore
- test/fixtures/pnpm-engine/.npmrc
- test/fixtures/pnpm-engine/package.json
- test/fixtures/pnpm-engine/pnpm-lock.yaml
- test/fixtures/pnpm-engine/server.js
- test/fixtures/pnpm-with-corepack-and-engine/.gitigore
- test/fixtures/pnpm-with-corepack-and-engine/.npmrc
- test/fixtures/pnpm-with-corepack-and-engine/package.json
- test/fixtures/pnpm-with-corepack-and-engine/pnpm-lock.yaml
- test/fixtures/pnpm-with-corepack-and-engine/server.js
- test/run
These changes build on top of [existing pnpm support](https://github.com/heroku/heroku-buildpack-nodejs/pull/1224) to use the version specified by the `engines.pnpm` field in `package.json`.
> pnpm support engines

- bin/report
- lib/builddata.sh
Forgot that it's not enough to annotate the build with metrics but that `bin/report` also requires some manual mappings to make these available so this PR adds those mappings.
> Capture pnpm metrics

- CHANGELOG.md
- lib/dependencies.sh
- test/run
Matches functionality already present for Yarn and NPM. Didn't include an additional flag to skip
pruning in contexts where it's needed at runtime,
as it's not necessary for my specific use-case and I wasn't sure of naming conventions here.
Unfortunately it's impossible for me to run unit tests on this at the moment. Several tests are failing locally, but those same tests also fail under the main branch, so I have to assume it's related to my dev environment (docker on an arm64 mac). Ideally, running on CI will give us useful information.
I can confirm that it works in our actual use-case.
> Skip dev dependency pruning on tests with PNPM

- test/run
Explicitly checking the exit code instead of using `assertCapturedSuccess` since tests started failing because the following message is now emitted to `stderr` by the `browserlist` package:
```
WARN  Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
> Fix failing integration test

- .github/workflows/inventory.yml
The use-app-token action is deprecated: https://github.com/heroku/use-app-token-action/pull/17
GUS-W-16159724
> Use actions/create-github-app-token instead of heroku/use-app-token

- CHANGELOG.md
- bin/compile
- lib/environment.sh
- test/run
If the user has not set a custom `NODE_OPTIONS` environment variable, we automatically set `NODE_OPTIONS="--max_old_space_size=2560"` in the build environment. This setting helps to mitigate OOM issues that sometimes occur when asset compilation tools are used. 
This setting is currently limited to the Node.js Buildpack's environment. To propagate this setting to downstream buildpacks such as the Ruby Buildpack (which sometimes requires Node to run asset compilation tasks too), this PR writes the setting to the `<buildpack_dir>/export` file. It will not export the setting if the user already has a custom `NODE_OPTIONS` environment variable.
> Export `NODE_OPTIONS` env default to downstream buildpacks

- CHANGELOG.md
- lib/dependencies.sh
- test/fixtures/pnpm-workspace-binaries/package.json
- test/fixtures/pnpm-workspace-binaries/packages/one/package.json
- test/fixtures/pnpm-workspace-binaries/packages/two/package.json
- test/fixtures/pnpm-workspace-binaries/pnpm-lock.yaml
- test/fixtures/pnpm-workspace-binaries/pnpm-workspace.yaml
- test/run
Noticed this issue on an internal application where the pruning step would misbehave if the application used pnpm workspaces. Checking the docs confirms that the prune command does not support recursive execution on a monorepo currently. This PR adds code to detect when a pnpm workspace is configured and, if so, will skip the pruning step.
> Skip pruning for pnpm workspaces since it's not supported

- .github/workflows/check_changelog.yml
- .github/workflows/ci.yml
- .github/workflows/hatchet_app_cleaner.yml
- .github/workflows/inventory.yml
Now that Ubuntu 24.04 images are available on GitHub Actions, we can update from the Ubuntu 22.04 images.
See also:
https://github.com/actions/runner-images/issues/9848
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
https://salesforce.quip.com/bu6UA0KImOxJ#temp:C:GZRd13d2ce2d455470495cbd34cf
GUS-W-16238120.
> Update CI to Ubuntu 24.04 runner images

- CHANGELOG.md
- bin/test
Folks using `pnpm` and Heroku CI may be surprised with strange error messages like `This project is configured to use ${result.spec.name} because ${result.target} has a "packageManager" field`. This is because our `bin/test` script is trying to run `npm test` on an app managed with `pnpm`.
Resolves #1307.
/cc @julianduque
> Support Heroku CI tests with pnpm

- test/fixtures/yarn-2-with-node-modules/package.json
With the upcoming [default node version change](https://github.com/heroku/heroku-buildpack-nodejs/pull/1341), this particular test fixture causes a test failure ([due to this deprecation warning](https://nodejs.org/api/deprecations.html#DEP0047)).
Explicitly set the node engine version to `20.x` for now (to prepare the fixture for the upcoming upgrade).
> Set yarn-2-with-node-modules node engine to 20.x

- CHANGELOG.md
- lib/binaries.sh
- test/run
Node.js 22.x is now the Active LTS release line as of 10-29-2024 ([source](https://github.com/nodejs/Release)). In accordance with our support policy, it should be the default version.
Fixes #1339
> Update default Node.js version to 22.x

- CHANGELOG.md
- lib/environment.sh
Buildpacks that run `npm install` or `yarn install` after the Node.js buildpack runs won't get the default value we set in #1347. This also exports the value for later buildpacks.
> Also export `UV_USE_IO_URING` for later buildpacks

- CHANGELOG.md
- lib/binaries.sh
- test/fixtures/corepack-integrity-keys/README.md
- test/fixtures/corepack-integrity-keys/package.json
- test/fixtures/corepack-integrity-keys/pnpm-lock.yaml
- test/fixtures/pnpm-unknown-version/pnpm-lock.yaml
- test/run
This is a workaround for Node versions that bundle a version of Corepack that is affected by recent changes to npm's public signing keys.
> Update npm registry keys for Corepack

- CHANGELOG.md
- lib/environment.sh
Other buildpacks  (e.g.; mainly Ruby but it could be others) frequently use the Node.js buildpack to provide asset compilation. In cases where Corepack is used to install and use a Node.js package manager like Yarn or pnpm, downstream buildpacks will not be able to properly find the Corepack downloaded package manager from the Node.js buildpack. This is because Corepack shims for each package manager will check in `COREPACK_HOME` to determine if the requested package manager is already present before downloading.
Exporting the `COREPACK_HOME` environment variable to downstream buildpacks will ensure that Corepack will not attempt to download the requested package manager twice.
This was tested using a newly created Rails 7 app configured with …
> Export `COREPACK_HOME` to downstream buildpacks

- .github/dependabot.yml
- .github/workflows/inventory.yml
The full-version Git tags used by Actions are mutable (as seen in recent events in the wider GitHub Actions community), so pinning third-party Actions to a SHA is recommended:
https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
The version tag has been added after the pin as a comment (as a readability aid) in a format that Dependabot will keep up to date: https://github.com/dependabot/dependabot-core/issues/4691
I've also enabled Dependabot grouping for GitHub Actions updates to reduce PR noise.
GUS-W-18051077.
> Pin SHA of third-party GitHub Actions

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- lib/failure.sh
- makefile
- spec/hatchet/stack_spec.rb
As [announced here](https://devcenter.heroku.com/changelog-items/3230), the `heroku-20` stack is no longer supported for builds on Heroku. This PR drops all references for the now end-of-life stack.
> Heroku-20 Stack End-of-life

- CHANGELOG.md
- bin/release
- bin/report
Update release script to not contribute a default process type if any `mcp` entries are present in the `Procfile`
> Update default output of bin/release

- .github/workflows/ci.yml
- .github/workflows/hatchet_app_cleaner.yml
Seeing automation failures with:
```
excon-1.2.8 requires ruby version >= 3.1.0, which is incompatible with the
current version, ruby 2.7.8p225
```
e.g.; https://github.com/heroku/heroku-buildpack-nodejs/actions/runs/16682096519/job/47222966798?pr=1445
This PR updates the version of Ruby used in these automation workflows to 3.1.
[W-19271094](https://gus.lightning.force.com/a07EE00002JhXs8YAF)
> Upgrading the Ruby version used by automation

- .github/workflows/ci.yml
- lib/failure.sh
- lib/monitor.sh
- makefile
- test/fixtures/error-openssl-unsupported-algorithm-in-webpack/index.js
- test/fixtures/error-openssl-unsupported-algorithm-in-webpack/package-lock.json
- test/fixtures/error-openssl-unsupported-algorithm-in-webpack/package.json
- test/fixtures/error-openssl-unsupported-algorithm-in-webpack/webpack.config.js
- test/fixtures/error-openssl-unsupported-algorithm/package-lock.json
- test/fixtures/error-openssl-unsupported-algorithm/package.json
- test/run
This PR classifies both a generic and Webpack variants of this type of error.
- detects when a `ERR_OSSL_EVP_UNSUPPORTED` error happens during the buildpack operation
- provides an error message with appropriate detail and remediation steps
- classifies the error as `openssl-unsupported-algorithm`
- detects when a `ERR_OSSL_EVP_UNSUPPORTED` error happens during Webpack command execution
- provides an error message with appropriate detail, remediation steps, and resource links
- classifies the error as `openssl-unsupported-algorithm-webpack`
[W-19282445](https://gus.lightning.force.com/a07EE00002JlBxLYAV)
> Classify openssl unsupported cryptographic algorithm error

- CHANGELOG.md
- bin/report
- test/fixtures/node-14/package.json
- test/run
> Fix YAML control character escaping

- CHANGELOG.md
- bin/compile
- bin/report
- lib/binaries.sh
- test/run
Also cleans up some call sites that need to examine node major and minor numbers.
> Add `node_version_major` to metrics

- test/fixtures/corepack-invalid-package-manager/package.json
- test/run
The integration test suite is failing for the classic Node.js buildpack due to a change in behavior from the Yarn package registry where, if a invalid Yarn version is requested, it nows installs a dummy version of Yarn via corepack that prints a custom error message instead of failing the install. See https://github.com/heroku/heroku-buildpack-nodejs/actions/runs/18191223667/job/51793169553
This PR switches the test to now use `pnpm` for this use case.
[W-19801950](https://gus.lightning.force.com/a07EE00002MkEleYAF)
> Fix test for invalid corepack version error

- .github/CODEOWNERS
Now that the repo has Rust components, so that it matches that for the CNB:
https://github.com/heroku/buildpacks-nodejs/blob/f5bcb5f3af82b136a82e989a0a72b16a99bd2f16/.github/CODEOWNERS#L10-L11
...and ensures the review request for PRs like #1488 go to the language owner rather than the languages team alias.
> Add Cargo.toml/lock to CODEOWNERS
