bin/compile, bin/test, test/dynamic-procfile/package.json
Resolves https://github.com/heroku/heroku-buildpack-nodejs/issues/163
=> test and implementation for dynamically-created Procfile support

bin/test
Look for `node` and `node_modules` directories.
This, just compatible with the updated buildpack: https://github.com/heroku/heroku-buildpack-nodejs/pull/144
=> more specific tests

bin/common.sh, bin/compile, bin/test, bin/warnings.sh, test/old-npm/package.json
Resolves https://github.com/heroku/heroku-buildpack-nodejs/issues/162
=> Warn old npm

bin/compile, bin/test, test/failing-build/package.json
Resolves https://github.com/heroku/heroku-buildpack-nodejs/issues/160
=> New announcement

bin/compile, bin/test, test/same-npm/package.json
Resolves https://github.com/heroku/heroku-buildpack-nodejs/issues/158
=> test and implementation for skipping replacement of npm

bin/common.sh, bin/compile, bin/test, bin/warnings.sh, test/npm-version-specific/package.json, test/old-npm/package.json
Warnings shouldn't all be applied in the same place, but they should be defined together.
=> split up warnings

bin/compile, bin/test, lib/build.sh, lib/common.sh, test/iojs/package.json
Resolves https://github.com/heroku/heroku-buildpack-nodejs/issues/180
=> Iojs engine

lib/build.sh, lib/concurrency.sh, test/run
Set reasonable defaults for concurrency by detecting available dyno memory.
=> tests and implementation for WEB_CONCURRENCY

README.md
@hunterloftis adding art to the readme.
=> Adding buildpack art

CHANGELOG.md, lib/build.sh
Easier to read messages on build failure.
=> Failure messaging

bin/compile, lib/failure.sh, lib/output.sh, test/fixtures/bower-angular-resolution/bower.json, test/fixtures/bower-angular-resolution/package.json, test/fixtures/missing-grunt/README.md, test/fixtures/missing-grunt/package.json, test/run
- tee output to a logfile
- on build failure, grep the log for string symptoms of common errors
- suggest solutions in the failure message
=> Detect errors

CHANGELOG.md, bin/compile, lib/failure.sh, test/run
- empties cache whenever cache is disabled (instead of wasting time / S3 space)
- adds bower_components as a default cache target
=> Cache strict with bower

lib/output.sh, makefile
Resolves https://github.com/heroku/heroku-buildpack-nodejs/issues/273
=> test and implementation for more robust output formatting

CHANGELOG.md, bin/compile, lib/dependencies.sh, test/fixtures/pre-post-build-scripts/README.md, test/fixtures/pre-post-build-scripts/package.json, test/run
Updating https://github.com/heroku/heroku-buildpack-nodejs/pull/293
=> Fiznool master

bin/compile, lib/dependencies.sh, test/fixtures/pre-post-build-scripts/README.md, test/fixtures/pre-post-build-scripts/package.json, test/run
=> Added heroku prebuild and postbuild scripts

README.md
updating the buildpack image to align better with marketing (and fix the code block in the background)
=> Updating image to align with marketing

.travis.yml, makefile
Cedar-10 is deprecated. Let's not test it by default.
=> only test cedar-14 by default

lib/environment.sh, lib/failure.sh, test/fixtures/echo-lang/package.json, test/run
=> test and implementation for blacklisting LANG; fixed failure tests

CHANGELOG.md
=> changelog for v91

CHANGELOG.md, bin/compile, bin/test-compile, lib/cache.sh, lib/dependencies.sh, lib/environment.sh, lib/failure.sh, test/run
=> better caching for yarn

bin/compile, lib/cache.sh, lib/dependencies.sh, lib/failure.sh, test/run
Imports the stdlib and uses it to measure:
- failure counts
- warning counts
- bin type (iojs/node, yarn/npm) and version counts
- cache status
- module install time split between valid and disabled/busted caches
- module size
=> instrument basic metrics

makefile
- Drop testing support for Cedar-10
- Add testing support for Heroku-16
Fixes #382
=> Test Heroku-16 stack

bin/compile, lib/dependencies.sh
- Log every time the compile succeeds
- Add log information about which build scripts are being used
=> Add new metrics logging

test/run
If Travis passes this build it should be good to go
=> Update tests for Node 8

.travis.yml
This reduces the wall-clock time from 16 minutes to 9 minutes.
=> Test Heroku-16 and Cedar-14 in parallel on Travis

.github/CODEOWNERS
Make it easier to get review from someone on the team:
https://github.com/blog/2392-introducing-code-owners
=> add @heroku/languages as code owners

README.md
Fixes https://github.com/heroku/heroku-buildpack-nodejs/issues/470
=> Update stack documentation

lib/binaries.sh
=> Update default yarn version to 1.x

lib/environment.sh
I'd like to know how many people have set this manually
=> Add metrics around installing devDependencies

bin/compile, lib/failure.sh
=> Remove yarn warning

lib/binaries.sh, test/fixtures/unmet-dep/package.json, test/run
=> Bump default version of Node to Node 8

lib/failure.sh
Adds detection for ~15 specific errors
=> Add more detection for known error types

spec/fixtures/repos/node-10-metrics/Procfile, spec/fixtures/repos/node-10-metrics/package.json, spec/fixtures/repos/node-10-metrics/src/index.js, spec/fixtures/repos/node-10/Procfile, spec/fixtures/repos/node-10/app.json, spec/fixtures/repos/node-10/package.json, spec/fixtures/repos/node-10/src/index.js, spec/fixtures/repos/node-6/Procfile, spec/fixtures/repos/node-6/app.json, spec/fixtures/repos/node-6/package.json, spec/fixtures/repos/node-6/src/index.js, spec/fixtures/repos/node-8-metrics/Procfile, spec/fixtures/repos/node-8-metrics/package.json, spec/fixtures/repos/node-8-metrics/src/index.js, spec/fixtures/repos/node-8/Procfile, spec/fixtures/repos/node-8/app.json, spec/fixtures/repos/node-8/package.json, spec/fixtures/repos/node-8/src/index.js, spec/fixtures/repos/node-9-metrics/Procfile, spec/fixtures/repos/node-9-metrics/package.json, spec/fixtures/repos/node-9-metrics/src/index.js, spec/fixtures/repos/node-9/Procfile, spec/fixtures/repos/node-9/app.json, spec/fixtures/repos/node-9/package.json, spec/fixtures/repos/node-9/src/index.js
To reduce noise I split the fixtures I'll be using for Hatchet tests out of https://github.com/heroku/heroku-buildpack-nodejs/pull/552
This adds the code for the fixture apps to `spec/fixtures/repos/` but does nothing with it yet
=> Add hatchet fixtures

Gemfile, Gemfile.lock, etc/hatchet.sh, makefile, spec/ci/node_10_metrics_spec.rb, spec/ci/node_10_spec.rb, spec/ci/node_6_spec.rb, spec/ci/node_8_metrics_spec.rb, spec/ci/node_8_spec.rb, spec/ci/node_9_metrics_spec.rb, spec/ci/node_9_spec.rb, spec/nodebin/node_vX_metrics_spec.rb, spec/nodebin/node_vX_spec.rb, spec/spec_helper.rb
@schneems merged my changes so we can use the published version now
=> Use latest hatchet instead of git branch

test/run
I need to rework this test so it's less flakey with new versions, but for now just get it working again
=> Fix CI tests

.travis.yml, bin/compile, lib/cache.sh, makefile
First PR to addressing https://github.com/heroku/heroku-buildpack-nodejs/issues/525
=> Add bin/compile to shellcheck check

CHANGELOG.md
Changelog is also missing v141 and v142…
=> Add v140 to changelog

bin/compile
Removes the breaking change warning now that the change has been out for several weeks
=> Remove breaking change warning

cmd/resolve-version/main.go, cmd/resolve-version/main_integration_test.go, cmd/resolve-version/main_test.go, makefile
Depends on #650 
This adds a function that will fetch all of the items in a public S3 bucket that match a given prefix. It handles paging and parsing the xml response for you.
=> Add helper function for fetching S3 objects

cmd/resolve-version/main.go, cmd/resolve-version/main_test.go
[The golang library we're using](https://github.com/Masterminds/semver) for semver matching requires ranges to be separated by a comma. Ex: `>=8.10, <11` 
while [the Node package we are currently using](https://www.npmjs.com/package/semver) supports these ranges with only a space. Ex: `>=8.10 <11`
This detects this case and works around this limitation by re-writing the semver range with a comma in this case.
=> [semver] Work around missing library functionality

CHANGELOG.md
=> update master changelog

CHANGELOG.md
Released v165 with default to Node 12.
=> update changelog for new release

CHANGELOG.md
=> update changelog for v167 release

CHANGELOG.md, features
https://github.com/heroku/heroku-buildpack-nodejs/issues/522
=> Test npm ci with 20% of builds

CHANGELOG.md, features
- change npm ci to 50%
- change yarn cache to 100%
=> Up feature flag test groups

CHANGELOG.md
Update CHANGELOG for v171 release.
=> v171 release

CHANGELOG.md
=> move latest changes to v172

CHANGELOG.md, lib/failure.sh
past blog post is outdated, update to use devcenter article instead
=> update git important bits url

CHANGELOG.md, README.md, etc/hatchet.sh, etc/publish.sh, lib/failure.sh
Updates docs, CHANGELOG, and other scripts to use `main`.
=> update branch references to use main [changelog skip]

CHANGELOG.md
=> update CHANGELOG for v175 release

CHANGELOG.md, features
Up 100% of builds to use npm ci.
=> up usage of npm ci to 100% of builds

CHANGELOG.md
~~pending https://github.com/heroku/heroku-buildpack-nodejs/pull/842~~ done!
=> update CHANGELOG for v176 release

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement-request.md
=> Update issue templates [changelog skip]

CHANGELOG.md, bin/report
Follow up to https://github.com/heroku/heroku-buildpack-nodejs/pull/855 for actually sending it to Honeycomb.
=> Send data to bin/report for testing of resolve-version

CHANGELOG.md
Adding one more pull request to this release.
=> release v177

CHANGELOG.md, inventory/node.toml
Releases the latest versions of Node.
=> add latest Node 15.3.0 and 12.20.0

CHANGELOG.md, inventory/node.toml
Add 14.15.3 and 15.5.0 to Node inventory.
=> add 14.15.3 and 15.5.0 for node inventory

CHANGELOG.md
=> Edit format of CHANGELOG release header [changelog skip]

CHANGELOG.md, inventory/node.toml
Update local inventory for next node versions
=> add 10.23.3, 12.20.2 and 14.5.5 to inventory

CHANGELOG.md, lib/failure.sh
=> Corrects tiny typo in conflicting lockfile failure message

CHANGELOG.md
There are a few recent changes that need to be released: #938, #901, #913, #936
=> Prepare v187 release

CHANGELOG.md, bin/compile
Fixes https://github.com/heroku/heroku-buildpack-nodejs/issues/884
=> Always use local yarn cache with yarn 2

CHANGELOG.md
This will release #888 and #940 as v188.
=> Prepare release v188

CHANGELOG.md
=> Prepare release v189

CHANGELOG.md
This prepares v192 for release, which will include #985 and #987.
GUS-W-10519616
=> Prepare v192 for release

CHANGELOG.md
To pick up #1013, #1016 & #1017.
GUS-W-11283397.
=> Release v198

CHANGELOG.md, yarn2-plugins/prune-dev-dependencies/package-lock.json, yarn2-plugins/prune-dev-dependencies/package.json
Release of #1040
This PR also addresses the following dependabot security alerts:
- https://github.com/heroku/heroku-buildpack-nodejs/security/dependabot/11
- https://github.com/heroku/heroku-buildpack-nodejs/security/dependabot/4
- https://github.com/heroku/heroku-buildpack-nodejs/security/dependabot/12
=> Prepare release v200

CHANGELOG.md
This will release #1045 and #1046.
[W-11854649](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE000017vi0fYAA)
=> Prepare release - v201

CHANGELOG.md, inventory/node.toml
- includes fixed node inventory for 18.15.0
=> Release v205

CHANGELOG.md
This updates the changelog and makes the latest inventory updates available.
=> Prepare v206 release

CHANGELOG.md
This updates the changelog and makes the latest inventory updates available.
=> Prepare v207 Release

CHANGELOG.md
Prepare release v208 with node version 19.9.0.
=> Prepare release v208

CHANGELOG.md
This prepares v217 with the latest 18.x release from Node.js.
=> Prepare v217 for release

CHANGELOG.md
Includes changes from:
- https://github.com/heroku/heroku-buildpack-nodejs/pull/1129
=> Prepare v219 for release

CHANGELOG.md
=> Prepare Release v222

CHANGELOG.md
=> Prepare release v223

CHANGELOG.md
=> Prepare release v224

CHANGELOG.md
Includes the following changes:
- #1171 
- #1170
=> Prepare release v228

.github/workflows/hatchet_app_cleaner.yml, .github/workflows/prepare_release.yml
Adds automation to prepare a classic buildpack release. See https://github.com/heroku/languages-github-actions/pull/184
=> Prepare release automation

CHANGELOG.md, bin/compile, lib/cache.sh, lib/dependencies.sh, lib/environment.sh, lib/failure.sh, lib/monitor.sh, test/run
Remove calls to unsupported metrics format:
- `mcount` functionality is superseded by `meta_set`
- `mtime` is superseded by `meta_time`
- `mmeasure` is superseded by `meta_set` 
[W-19315650](https://gus.lightning.force.com/a07EE00002K1ixfYAB)
=> Cleanup metrics

.github/workflows/inventory.yml
Depends on https://github.com/heroku/buildpacks-nodejs/pull/1181
[W-18709485](https://gus.lightning.force.com/a07EE00002FcEsUYAV)
=> Switch to new inventory update binary
